require('IGCMS', function () { IGCMS.InputVar = {}; IGCMS.InputVar.data = [
{name:'nabidka-jidlo',data:[
{data:'2019-10-18',name:'Srnčí po Burgundsku',desc:'Srnčí kýta (váleček) dušená na červeném víně s kořenovou zeleninou, žampiony a stříbrnými cibulkami, šťouchané brambory s pórkem a slaninou.',price:'229 Kč'},
{data:'2019-10-17',name:'Králík na smetaně',desc:'Králík z českého chovu, naše karlovarské knedlíky, citron, brusinky.',price:'219 Kč'},
{data:'2019-10-16',name:'Krůta pečená na másle',desc:'Šťouchané brambory, americká chlebová nádivka s jablky, řapíkatým celerem a rozinkami, krémový špenát, přírodní šťáva.',price:'219 Kč'},
{data:'2019-10-15',name:'Holandský řízek',desc:'Mleté vepřové maso se sýrem gouda smažené v trojobalu dozlatova, mléčná bramborová kaše, zelný salát s okurkami a rajčaty.',price:'189 Kč'},
{data:'2019-10-14',name:'Tagliatelle s lososem',desc:'Italské široké nudle s kousky lososa v delikátní smetanové omáčce s hráškem.',price:'179 Kč'},
{data:'2019-10-11',name:'Pfeffer steak',desc:'Hovězí roštěná krájená na tenké plátky v delikátní pepřové omáčce s červeným vínem, paprikou, rajčaty, cibulí, česnekem a hráškovým luskem, jasmínová rýže.',price:'219 Kč'},
{data:'2019-10-10',name:'Telecí guláš',desc:'Telecí kýta krájená na kostky dušená v delikátní smetanové omáčce s cibulí, paprikou a bílým vínem, naše špecle.',price:'189 Kč'},
{data:'2019-10-09',name:'Pečený králík',desc:'Na bílém víně s kořenovou zeleninou a slaninou, naše bramborové knedlíky, kyselé zelí, smažená cibulka.',price:'219 Kč'},
{data:'2019-10-08',name:'Geschnetzeltes',desc:'Švýcarská specialita, na nudličky krájená vepřová panenka v delikátní smetanové omáčce s bílým vínem a žampiony, bramborové rösti.',price:'179 Kč'},
{data:'2019-10-07',name:'Smažený karbanátek',desc:'V trojobalu dozlatova smažený karbanátek z mletého hovězího a vepřového masa, česnek, majoránka, mléčná bramborová kaše, míchaný salát.',price:'179 Kč'},
{data:'2019-10-04',name:'Konfitovaná krkovice',desc:'Mléčná bramborová kaše sypaná jarní cibulkou, rajčatový salát.',price:'199 Kč'},
{data:'2019-10-03',name:'Karlovarský guláš',desc:'Z vyzrálé uruguayské hovězí kýty s červenou paprikou, cibulí a smetanou, naše vídeňské knedlíky.',price:'179 Kč'},
{data:'2019-10-02',name:'Řízek z krkovice, 200 g',desc:'V trojobalu dozlatova smažený řízek z libové krkovice, náš bramborový salát, citron.',price:'189 Kč'},
{data:'2019-10-02',name:'Segedínský guláš',desc:'Krájená vepřová plec ve smetanové omáčce s kysaným zelím a červenou paprikou, naše houskové knedlíky.',price:'169 Kč'},
{data:'2019-09-30',name:'Pečené hovězí hrudí (brisket)',desc:'Vyzrálé hovězí hrudí z Austrálie (grain fed 140 dní), krájené na plátky, lahůdkové brambory, brokolice na másle, přírodní šťáva, naše tatarská omáčka.',price:'249 Kč'},
{data:'2019-09-30',name:'Španělský ptáček',desc:'Z uruguayské hovězí kýty, jasmínová rýže.',price:'189 Kč'},
{data:'2019-09-27',name:'Pečená kachna s jablky',desc:'Naše vídeňské knedlíky, červené vinné zelí a kyselé zelí.',price:'199 Kč'},
{data:'2019-09-26',name:'Hovězí na česneku',desc:'Vyzrálá uruguayská hovězí kýta, naše bramborové knedlíky, špenát.',price:'189 Kč'},
{data:'2019-09-24',name:'Smažený karbanátek z lososa',desc:'Karbanátek (slanina, cibule, koření) obalený v trojobalu smažený dozlatova, mléčná bramborová kaše, citron, míchaný salát.',price:'219 Kč'},
{data:'2019-09-23',name:'Hovězí na houbách',desc:'Falešná svíčková dušená s lesními houbami, jasmínová rýže, máslový hrášek.',price:'189 Kč'},
{data:'2019-09-23',name:'BBQ vepřová žebírka',desc:'Vepřová žebírka pečená v BBQ omáčce, hranolky, coleslaw.',price:'179 Kč'},
{data:'2019-09-20',name:'Pečený králík z francouzské farmy',desc:'Pomalu pečený králík s cibulí, česnekem a tymiánem, naše bramborové knedlíky, smažená cibulka, červené vinné zelí.',price:'229 Kč'},
{data:'2019-09-20',name:'Srnčí ragú na červeném víně',desc:'Krájený srnčí váleček (z kýty) s červeným vínem, žampiony a cibulkami, šťouchané brambory s cibulí a slaninou.',price:'219 Kč'},
{data:'2019-09-17',name:'Vepřové na paprice',desc:'Kousky vepřové panenky v delikátní smetanové omáčce s červenou paprikou, naše špecle.',price:'189 Kč'},
{data:'2019-09-16',name:'Pečená medová šunka',desc:'Vepřová burgundská šunka potřená medem s mletým hřebíčkem, mléčná bramborová kaše s cibulkou na sádle, míchaný salát.',price:'179 Kč'},
{data:'2019-09-16',name:'Konfitované kachní stehno',desc:'Pomalu pečené maso v kachním sádle, naše houskové knedlíky, červené vinné zelí.',price:'249 Kč'},
{data:'2019-09-16',name:'Konfitované kachní stehno',desc:'Pomalu pečené maso v kachním sádle, naše houskové knedlíky, červené vinné zelí, smažená cibulka.',price:'249 Kč'},
{data:'2019-09-16',name:'Pečená medová šunka',desc:'Vepřová šunka potřená medem s mletým hřebíčkem, mléčná bramborová kaše, míchaný salát.',price:'199 Kč'},
{data:'2019-09-13',name:'Vepřový guláš',desc:'Pomalu dušená vepřová, naše houskové knedlíky.',price:'179 Kč'},
{data:'2019-09-12',name:'Kachní směs',desc:'Kousky kachního masa se zeleninou, bambusovými výhonky, sojovou omáčkou a japonskou omáčkou Teriyaki, jasmínová rýže.',price:'199 Kč'},
{data:'2019-09-12',name:'Beef stroganoff',desc:'Uruguayská hovězí svíčková krájená na nudličky v delikátní smetanové omáčce se žampiony a kyselou okurkou, jasmínová rýže.',price:'219 Kč'},
{data:'2019-09-11',name:'Smažené nugety z lososa',desc:'Mléčná bramborová kaše, míchaný zeleninový salát.',price:'199 Kč'},
{data:'2019-09-10',name:'Pfeffer steak',desc:'Vyzrálá uruguayská hovězí svíčková krájená na tenké plátky v delikátní pepřové omáčce s červeným vínem, paprikou, rajčaty, cibulí, česnekem a cukrovým hráškem, jasmínová rýže.',price:'219 Kč'},
{data:'2019-09-09',name:'Burger s trhaným masem',desc:'BBQ trhané vepřové v sezamové bulce, česnekový dip, ledový salát, rajče, červená cibule, hranolky, Coleslaw, Jalapeño papričky.',price:'219 Kč'},
{data:'2019-09-06',name:'Beef Steak Wellington',desc:'Vyzrálá uruguayská hovězí svíčková zapečená v listovém těstě se směsí hub, slaniny, cibule a petrželky, šťouchané brambory, krémový špenát, přírodní šťáva.',price:'259 Kč'},
{data:'2019-09-05',name:'Srnčí guláš',desc:'Na kostky krájený srnčí váleček dušený s cibulí a červeným vínem, naše špecle, mrkev s rozinkami.',price:'219 Kč'},
{data:'2019-09-05',name:'Srnčí guláš',desc:'Na kostky krájený srnčí váleček dušený s cibulí a červeným vínem, naše karlovarské knedlíky, mrkev s rozinkami.',price:'219 Kč'},
{data:'2019-09-05',name:'BBQ vepřová žebírka',desc:'Vepřová žebírka pečená v naší BBQ omáčce, hranolky, Coleslaw.',price:'189 Kč'},
{data:'2019-09-03',name:'Hovězí na smetaně zvaná „svíčková“',desc:'Vyzrálá irská falešná  svíčková v delikátní smetanové omáčce, naše houskové knedlíky, citron, brusinky.',price:'219 Kč'},
{data:'2019-09-03',name:'Smažená treska',desc:'Kousky tresky tmavé ve vinném těstíčku, hranolky, tatarská omáčka, citron.',price:'189 Kč'},
{data:'2019-09-02',name:'Pečené kuře z pece',desc:'Pomalu pečené v naší unikátní peci na dřevě s kouřovým aromatem, mléčná bramborová kaše, míchaný zeleninový salát s balkánským sýrem.',price:'199 Kč'},
{data:'2019-08-30',name:'Francouzská kachní roláda',desc:'Pomalu pečená roláda z vykostěných kachen s provensálským kořením, naše bramborové knedlíky, bílé kysané zelí a červené vinné zelí, smažená cibulka.',price:'229 Kč'},
{data:'2019-08-30',name:'Hovězí na smetaně zvaná „svíčková“',desc:'Vyzrálá irská falešná svíčková v delikátní smetanové omáčce, naše houskové knedlíky, citron, brusinky.',price:'219 Kč'},
{data:'2019-08-28',name:'Srnčí ragú',desc:'Na kousky krájený váleček z kýty, dušený s liškami a žampiony ve smetanové omáčce z bílého vína, naše špekové knedlíky.',price:'199 Kč'},
{data:'2019-08-26',name:'Roštěná Esterházy',desc:'Plátky roštěné dušené v delikátní smetanové omáčce s kořenovou zeleninou, kapary a kyselou okurkou, naše houskové knedlíky nebo špecle.',price:'199 Kč'},
{data:'2019-08-26',name:'Roštěná Esterházy',desc:'Plátky roštěné dušené v delikátní smetanové omáčce s kořenovou zeleninou, kapary a kyselou okurkou, naše špecle.',price:'219 Kč'},
{data:'2019-08-22',name:'Fried Rice',desc:'Pražená rýže s drůbežím masem, zeleninou a žampiony, sázené vejce, kyselá okurka.',price:'179 Kč'},
{data:'2019-08-22',name:'Hamburská vepřová kýta',desc:'Dušený ořech z vepřové kýty v delikátní smetanové omáčce se šunkou a kyselými okurkami, náš houskový knedlík.',price:'189 Kč'},
{data:'2019-08-20',name:'Drum Sticks',desc:'Pomalu pečené vepřové lýtko na cibuli, šťouchané brambory, kukuřice O\'Brien.',price:'189 Kč'},
{data:'2019-08-19',name:'Krůtí roláda se žampiony',desc:'Pečená roláda s masovou fáší a žampiony, přírodní šťáva, mléčná bramborová kaše, okurkový salát.',price:'189 Kč'},
{data:'2019-08-15',name:'Pečené kuře na másle',desc:'Šťouchané brambory, brokolice na másle.',price:'179 Kč'},
{data:'2019-08-14',name:'Řízek z krkovice',desc:'V trojobalu dozlatova smažený řízek z libové krkovice, vařené brambory s máslem, kyselá okurka.',price:'199 Kč'},
{data:'2019-08-14',name:'Těstoviny s lososem',desc:'Těstoviny tagliatelle v delikátní smetanové omáčce s kousky lososa a mladého hrášku.',price:'179 Kč'},
{data:'2019-08-13',name:'Telecí na houbách',desc:'Dušené telecí maso v delikátní smetanové omáčce s lesními houbami, jasmínová rýže, máslový hrášek.',price:'199 Kč'},
{data:'2019-08-09',name:'Beef Stroganoff',desc:'Hovězí kýta krájená na nudličky v delikátní smetanové omáčce se žampiony a kyselou okurkou, hranolky.',price:'219 Kč'},
{data:'2019-08-09',name:'Pečená krkovice po selsku',desc:'Pomalu pečená vepřová krkovice s cibulí a česnekem, naše bramborové knedlíky, smažená cibulka, kyselé zelí.',price:'189 Kč'},
{data:'2019-08-08',name:'Vepřová žebra',desc:'Pečená v naší BBQ omáčce, hranolky, Coleslaw.',price:'179 Kč'},
{data:'2019-08-07',name:'Kuřecí roláda',desc:'Vykostěné kuře, plněné mletým masem a sušenými rajčaty, mléčná bramborová kaše, míchaný salát.',price:'199 Kč'},
{data:'2019-08-05',name:'Znojemská',desc:'Dušená vyzrálá uruguayská hovězí kýta v delikátní omáčce s tence krájenými kyselými okurkami, jasmínová rýže.',price:'189 Kč'},
{data:'2019-08-02',name:'Pečený králík z francouzské farmy',desc:'Pomalu pečený králík s cibulí, česnekem a tymiánem, naše bramborové knedlíky, červené vinné zelí, smažená cibulka.',price:'229 Kč'},
{data:'2019-07-31',name:'Grilovaný mletý telecí řízek',desc:'S provensálským kořením a česnekem, šťouchané brambory, okurkový salát.',price:'199 Kč'},
{data:'2019-07-29',name:'Vepřová plec na paprice',desc:'Delikátní smetanová omáčka s paprikou, naše špecle.',price:'179 Kč'},
{data:'2019-07-26',name:'Vepřové výpečky',desc:'Náš bramborový knedlík sypaný vídeňskou cibulkou, kysané zelí.',price:'189 Kč'},
{data:'2019-07-23',name:'Řízek z krkovice',desc:'V trojobalu dozlatova smažený řízek z libové krkovice, lahůdkové brambory opečené na másle s petrželkou, okurkový salát.',price:'189 Kč'},
{data:'2019-07-22',name:'Hovězí konfitovaná žebra',desc:'Pomalu pečená hovězí žebra s BBQ omáčkou, hranolky, kukuřice O´brien, česnekový dip.',price:'219 Kč'},
{data:'2019-07-22',name:'Hovězí na houbách',desc:'Dušený vyzrálý ořech z uruguayské kýty s lesními houbami, rýže s hráškem (Risi Bisi).',price:'199 Kč'},
{data:'2019-07-19',name:'Konfitované kachní stehno',desc:'Naše bramborové knedlíky, červené vinné zelí, smažená vídeňská cibulka.',price:'199 Kč'},
{data:'2019-07-17',name:'Hovězí na smetaně zvané „svíčková“',desc:'Ořech z vyzrálé uruguayské kýty v delikátní smetanové omáčce, naše karlovarské knedlíky, citron, brusinky.',price:'219 Kč'},
{data:'2019-07-15',name:'Hovězí guláš',desc:'Dušená libová hovězí kližka s cibulí a červenou paprikou, naše houskové knedlíky, cibulka.',price:'189 Kč'},
{data:'2019-07-15',name:'Hovězí guláš',desc:'Dušená libová hovězí kližka s cibulí a červenou paprikou, naše houskové knedlíky, smažená vídeňská cibulka.',price:'189 Kč'},
{data:'2019-07-12',name:'Rice-A-Roni Francisco Treat',desc:'Delikátní těstovinová rýže a jasmínová rýže s vepřovou kýtou, arašídy, řapíkatým celerem, hráškem a mrkví, strouhaný italský sýr.',price:'179 Kč'},
{data:'2019-07-11',name:'Tortilla s kuřecím masem',desc:'Placka z pšeničné mouky plněná kuřecím masem, ledovým salátem, rajčaty a omáčkou z čedaru, hranolky.',price:'189 Kč'},
{data:'2019-07-09',name:'Hovězí po Burgundsku',desc:'Dušené hovězí maso na červeném víně s mrkví, cibulkami a žampiony, šťouchané brambory s pórkem a slaninou.',price:'199 Kč'},
{data:'2019-07-08',name:'Kuřecí roláda',desc:'Vykostěné kuře, plněné mletým masem a sušenými rajčaty, mléčná bramborová kaše, okurkový salát.',price:'189 Kč'},
{data:'2019-07-08',name:'Kuřecí roláda',desc:'Vykostěné kuře, plněné sušenými rajčaty, mléčná bramborová kaše, okurkový salát.',price:'189 Kč'},
{data:'2019-07-05',name:'Fried Rice',desc:'Pražená rýže s kuřecím masem, zeleninou, žampiony, sázené vejce, kyselá okurka, smažená cibulka.',price:'179 Kč'},
{data:'2019-07-05',name:'Roastbeef',desc:'Při nízké teplotě dorůžova pečený vyzrálý uruguayský roštěnec, lahůdkové brambory s máslem a pažitkou, brokolice na másle, naše tatarská omáčka.',price:'229 Kč'},
{data:'2019-07-03',name:'Coq Au Vin',desc:'Francouzská úprava kuřete na červeném víně a koňaku, žampiony, stříbrné cibulky, šunka, těstoviny.',price:'179 Kč'},
{data:'2019-07-02',name:'Řecká Musaka',desc:'Zapečené mleté hovězí a vepřové maso, lilek, brambory, rajčata, sýr Gouda a parmazán. Na Balkáně jí dělá kde kdo, my jsme vybrali tu nejlepší.',price:'179 Kč'},
{data:'2019-07-01',name:'Míchaný salát se smaženými nugetami z lososa',desc:'Směs listových salátů, rajčata, okurka, ředkvičky, fajita dresink, v trojobalu dozlatova smažené nugety z lososa.',price:'189 Kč'},
{data:'2019-06-28',name:'Dukátové buchtičky',desc:'S vanilkovým krémem.',price:'169 Kč'},
{data:'2019-06-27',name:'Králík pečený po grenobelsku',desc:'Králík pečený s cibulí, slaninou, rajčaty a kapary, naše špecle, mrkev s rozinkami.',price:'199 Kč'},
{data:'2019-06-26',name:'Smažený holandský řízek',desc:'Mleté vepřové maso se sýrem Gouda smažené v trojobalu dozlatova, letní bramborový salát.',price:'179 Kč'},
{data:'2019-06-25',name:'Filet z tmavé tresky',desc:'Bez kůže opečený filet na másle, teplý čočkový salát s baby špenátem.',price:'189 Kč'},
{data:'2019-06-24',name:'Smažené řízečky z vepřové panenky',desc:'Mléčná bramborová kaše, zeleninový salát.',price:'219 Kč'},
{data:'2019-06-21',name:'Pfeffer Steak',desc:'Pravá hovězí svíčková krájená na tenké plátky v delikátní pepřové omáčce s červeným vínem, paprikou, rajčaty, cibulí, česnekem a hráškem, jasmínová rýže.',price:'219 Kč'},
{data:'2019-06-20',name:'Moravský vrabec',desc:'Naše bramborové knedlíky, kyselé zelí, smažená vídeňská cibulka.',price:'179 Kč'},
{data:'2019-06-20',name:'Náš moravský vrabec',desc:'Naše bramborové knedlíky, kyselé zelí, smažená vídeňská cibulka.',price:'179 Kč'},
{data:'2019-06-19',name:'Duck Fried Rice',desc:'Pražená rýže s kachním masem a zeleninou, smažená cibulka, kyselá okurka, sázené vejce.',price:'179 Kč'},
{data:'2019-06-18',name:'Pečená kuřecí roláda se špenátem',desc:'Mléčná bramborová kaše, míchaný zeleninový salát.',price:'189 Kč'},
{data:'2019-06-17',name:'Hovězí na smetaně zvané „svíčková“',desc:'Vyzrálá australská kýta v delikátní smetanové omáčce z kořenové zeleniny, naše houskové knedlíky, citron, brusinky.',price:'199 Kč'},
{data:'2019-06-14',name:'Carrot cake',desc:'Oblíbený americký dezert z mrkve, vlašských ořechů, kokosu a ananasu, čerstvý sýr, naše šlehačka.',price:'79 Kč'},
{data:'2019-06-13',name:'Naše halušky (strapačky)',desc:'S naším uzeným masem a kyselým zelím.',price:'169 Kč'},
{data:'2019-06-12',name:'Plněná paprika',desc:'Mleté hovězí a vepřové maso, rajská omáčka, jasmínová rýže.',price:'169 Kč'},
{data:'2019-06-11',name:'Pečený králík na česneku a cibuli',desc:'Pomalu pečený králík z Libochovic, naše špekové knedlíky, červené vinné zelí.',price:'199 Kč'},
{data:'2019-06-10',name:'Smažené nugety z lososa',desc:'Šťouchané brambory s jarní cibulkou, míchaný salát.',price:'189 Kč'},
{data:'2019-06-07',name:'Vepřové výpečky',desc:'Pomalu pečený vepřový bůček a plec s cibulí a česnekem, kyselé zelí, naše bramborové knedlíky, smažená cibulka.',price:'179 Kč'},
{data:'2019-06-07',name:'Hovězí na májovkách',desc:'Vyzrálá australská kýta dušená v delikátní smetanové omáčce s májovkami, naše karlovarské knedlíky.',price:'199 Kč'},
{data:'2019-06-05',name:'Vepřová plec na paprice',desc:'Pomalu dušená vepřová plec v delikátní smetanové omáčce s červenou paprikou, naše špecle.',price:'179 Kč'},
{data:'2019-06-04',name:'Smažené žampiony',desc:'Nové brambory z Doksan s máslem a pažitkou, okurkový salát, naše tatarská omáčka.',price:'179 Kč'},
{data:'2019-06-03',name:'Pečené vepřové paličky',desc:'Marinovaná část vepřového kolena s kostí, pečené s cibulí a česnekem, mléčná bramborová kaše, zeleninový salát.',price:'189 Kč'},
{data:'2019-06-03',name:'Vařené hovězí maso s koprovou omáčkou',desc:'Vyzrálá australská hovězí kýta ve smetanové omáčce s koprem, zdobená vařeným vejcem, naše houskové knedlíky.',price:'189 Kč'},
{data:'2019-05-29',name:'Domácí uzená krkovice',desc:'Naše bramborové knedlíky, smažená cibulka, kyselé zelí.',price:'179 Kč'},
{data:'2019-05-27',name:'Maďarská pečená kachna s jablky',desc:'Čtvrtka pomalu pečené, částečné vykostěné mladé kachny, náš bramborový knedlík, smažená cibulka, červené vinné zelí.',price:'199 Kč'},
{data:'2019-05-24',name:'Telecí na smetaně zvané „svíčková“',desc:'Dušená telecí kýta s kořenovou zeleninou, slaninou a smetanou, naše houskové knedlíky, citron, brusinky.',price:'219 Kč'},
{data:'2019-05-24',name:'Jelení guláš',desc:'Na kostky krájené, dušené jelení maso, červené víno, paprika, česnek, karlovarský knedlík a mrkev s rozinkami.',price:'199 Kč'},
{data:'2019-05-20',name:'Konfitovaná krkovice',desc:'V sádle pomalu pečená krkovice, mléčná bramborová kaše, míchaný zeleninový salát.',price:'179 Kč'},
{data:'2019-05-19',name:'Beef Stroganoff',desc:'Na nudličky krájená vyzrálá australská hovězí kýta, dušená v delikátní smetanové omáčce se žampiony a kyselou okurkou, hranolky.',price:'219 Kč'},
{data:'2019-05-16',name:'Konfitovaná krkovice',desc:'Mléčná bramborová kaše s medvědím česnekem, míchaný zeleninový salát.',price:'189 Kč'},
{data:'2019-05-14',name:'Řízek z krkovice',desc:'V trojobalu dozlatova smažený řízek z libové krkovice, šťouchané brambory, kyselá okurka, citron.',price:'199 Kč'},
{data:'2019-05-14',name:'Vepřová žebra',desc:'Pečená v BBQ omáčce, hranolky, Coleslaw.',price:'189 Kč'},
{data:'2019-05-13',name:'Jelen se šípkovou omáčkou',desc:'Jelení dušená kýta v omáčce z kořenové zeleniny, divokého koření, slaniny a šípkového džemu, naše karlovarské knedlíky, citron, brusinky.',price:'199 Kč'},
{data:'2019-05-13',name:'Hovězí na česneku',desc:'Vyzrálá australská kýta dušená na cibuli a česneku, naše kulaté bramborové knedlíky, krémový špenát, smažená cibulka.',price:'179 Kč'},
{data:'2019-05-09',name:'Hovězí na houbách',desc:'Dušená vyzrálá australská hovězí kýta s lesními houbami, rýže s hráškem (Risi Bisi).',price:'189 Kč'},
{data:'2019-05-08',name:'Vepřové výpečky',desc:'Pomalu pečený vepřový bůček a plec s cibulí a česnekem, kysané zelí, naše bramborové knedlíky, smažená cibulka.',price:'179 Kč'},
{data:'2019-05-07',name:'Trhaná hovězí kýta',desc:'Pomalu pečená australská hovězí kýta, mléčná bramborová kaše, přírodní šťáva, míchaný listový salát s paprikou a ředkvičkou.',price:'189 Kč'},
{data:'2019-05-06',name:'Pomalu pečená hovězí kýta',desc:'Vyzrálá australská hovězí kýta, pošírovaný zelený chřest se sýrovou omáčkou, lahůdkové brambory s máslem a pažitkou.',price:'199 Kč'},
{data:'2019-05-04',name:'Hamburská vepřová plec na smetaně',desc:'Delikátní smetanová omáčka z kořenovou zeleninou, restovaná burgundská šunka a kyselá okurka, naše houskové knedlíky.',price:'179 Kč'},
{data:'2019-05-02',name:'Pečená krůta',desc:'Porce mladé krůty s přírodní šťávou, náš bramborový knedlík, smažená vídeňská cibulka a krémový špenát.',price:'189 Kč'},
{data:'2019-05-02',name:'Znojemská hovězí pečeně',desc:'Vyzrálá australská hovězí kýta dušená ve vlastní šťávě se znojemskou okurkou, jasmínová rýže.',price:'179 Kč'},
{data:'2019-04-30',name:'Zelený chřest',desc:'Opečený s burgundskou šunkou, sýrová omáčka, vařené lahůdkové brambory s pažitkou.',price:'189 Kč'},
{data:'2019-04-29',name:'Konfitovaná krkovice',desc:'V bylinkové marinádě, mléčná bramborová kaše s medvědím česnekem, masová šťáva, smažená vídeňská cibulka.',price:'169 Kč'},
{data:'2019-04-29',name:'Konfitovaná krkovice',desc:'V bylinkové marinádě, mléčná bramborová kaše s medvědím česnekem, smažená vídeňská cibulka.',price:'229 Kč'},
{data:'2019-04-26',name:'Pečená selečí roláda',desc:'Naše bramborové knedlíky, kyselé zelí.',price:'199 Kč'},
{data:'2019-04-25',name:'Řízek z krkovice, 180 g',desc:'V trojobalu dozlatova smažený řízek z libové krkovice, vařené brambory s pažitkou a máslem, okurkový salát.',price:'189 Kč'},
{data:'2019-04-24',name:'Čevabčiči',desc:'Šťouchané brambory, cibulka, kyselá okurka, hořčice.',price:'179 Kč'},
{data:'2019-04-23',name:'Smažené nugety z lososa',desc:'V trojobalu smažené dozlatova, mléčná bramborová kaše pokapaná lanýžovým olejem, míchaný zeleninový salát.',price:'189 Kč'},
{data:'2019-04-22',name:'Pečené jarní kuřátko',desc:'Půlka pečeného kuřátka, lahůdkové brambory, nádivka s uzeným masem, medvědím česnekem a mrkvové pyré.',price:'179 Kč'},
{data:'2019-04-22',name:'Hovězí po Burgundsku',desc:'Dušená, stařená uruguayská kýta na červeném víně s mrkví, cibulkami a žampiony, mléčná bramborová kaše s baby špenátem.',price:'229 Kč'},
{data:'2019-04-19',name:'Hovězí po Burgundsku',desc:'Dušená, stařená uruguayská kýta na červeném víně s mrkví, cibulkami a žampiony, mléčná bramborová kaše s medvědím česnekem a baby špenátem.',price:'229 Kč'},
{data:'2019-04-18',name:'Crispy Salmon na teplém čočkovém salátu',desc:'Steak z lososa s křupavou kůží, vařená čočka s medvědím česnekem, baby špenát, jarní cibulka, balzamico.',price:'229 Kč'},
{data:'2019-04-17',name:'Vepřová panenka na houbách',desc:'Kousky vepřové panenky dušené v delikátní smetanové omáčce s lesními houbami, naše karlovarské knedlíky.',price:'199 Kč'},
{data:'2019-04-16',name:'Řízek z panenky',desc:'V trojobalu dozlatova na másle smažený řízek z vepřové panenky, mléčná bramborová kaše, míchaný zeleninový salát, citron.',price:'189 Kč'},
{data:'2019-04-15',name:'Burger s trhaným vepřovým',desc:'Pečená žebírko v BBQ omáčce, česnekový dip, ledový salát, smažená cibulka, hranolky, Coleslaw.',price:'179 Kč'},
{data:'2018-12-31',name:'Hovězí na houbách',desc:'Falešná hovězí svíčková ve smetanové omáčce s lesními houbami, naše karlovarské knedlíky.',price:'199 Kč'},
{data:'2018-12-31',name:'Hovězí na houbách',desc:'Falešná hovězí svíčková, naše karlovarské knedlíky.',price:'199 Kč'},
{data:'2018-12-27',name:'Pečená kachna',desc:'Naše bramborové knedlíky, červené vinné zelí, smažená vídeňská cibulka.',price:'199 Kč'},
{data:'2018-12-20',name:'BBQ trhané vepřové v sezamové bulce',desc:'Česnekový dip, ledový salát, rajče, smažené brambory, Coleslaw.',price:'189 Kč'},
{data:'2018-12-18',name:'Husí játra na cibulce',desc:'S mandlemi a žampiony, jasmínová rýže, máslový hrášek.',price:'169 Kč'},
{data:'2018-12-18',name:'Náš hovězí guláš',desc:'Dušený hovězí krk a kližka, karlovarský knedlík, mrkev s rozinkami.',price:'169 Kč'},
{data:'2018-12-14',name:'Hovězí na smetaně zvané „svíčková“',desc:'Uruguayská kýta Grain Fed v delikátní omáčce z kořenové zeleniny a smetany s divokým kořením, naše karlovarské knedlíky, citron, brusinky.',price:'199 Kč'},
{data:'2018-12-13',name:'Pivovarský řízek',desc:'Plátek vepřové pečeně plněný plísňovým sýrem smažený dozlatova v pivním těstíčku, vařené brambory s máslem a pažitkou, kyselé zelí.',price:'179 Kč'},
{data:'2018-12-12',name:'Konfitované kachní stehno',desc:'Naše bramborové knedlíky, červené vinné zelí, smažená cibulka.',price:'189 Kč'},
{data:'2018-12-10',name:'Pomalu pečená loupaná plec',desc:'Hovězí Top Blade USDA Prime pečená na zelenině, lahůdkové brambory na másle.',price:'189 Kč'},
{data:'2018-12-07',name:'Znojemská hovězí pečeně',desc:'Dušená vyzrálá uruguayská kýta v delikátní omáčce s tence krájenými kyselými okurkami, jasmínová rýže.',price:'179 Kč'},
{data:'2018-12-06',name:'Řízek z krkovice, 200 g',desc:'V trojobalu dozlatova smažený řízek z libové krkovice, náš bramborový salát, citron.',price:'189 Kč'},
{data:'2018-12-06',name:'Vepřové výpečky',desc:'Pomalu pečený vepřový bůček, kysané zelí, naše bramborové knedlíky, smažená vídeňská cibulka.',price:'179 Kč'},
{data:'2018-12-04',name:'Burger s trhaným vepřovým',desc:'BBQ trhané vepřové v sezamové bulce, česnekový dip, ledový salát, rajče, hranolky, coleslaw.',price:'189 Kč'},
{data:'2018-12-03',name:'Trhané vepřové',desc:'Pomalu přes noc pečená vepřová kýta, mléčná bramborová kaše, přírodní šťáva, míchaný salát.',price:'189 Kč'},
{data:'2018-11-30',name:'Beef Stew',desc:'V jednom hrnci dušený hovězí krk s mrkví, řapíkatým celerem, brambory a hráškem.',price:'179 Kč'},
{data:'2018-11-29',name:'Pečený králík na česneku a cibuli',desc:'Pečený králík z Libochovic, naše bramborové knedlíky, kyselé zelí, vídeňská cibulka.',price:'199 Kč'},
{data:'2018-11-28',name:'Coque Au Vin',desc:'Kohout na víně, francouzská úprava kuřete na červeném víně a koňaku, žampiony, stříbrné cibulky, šunka, těstoviny Fusilli, opečený toast.',price:'179 Kč'},
{data:'2018-11-27',name:'Fritto misto di mare',desc:'Smažené sépiové kroužky v těstíčku, treska tmavá a krevety se šťouchanými brambory, naše tatarská omáčka, citron.',price:'189 Kč'},
{data:'2018-11-26',name:'Náš hovězí guláš',desc:'Dušený hovězí krk s cibulí a červenou paprikou, domácí špecle, mrkev s rozinkami.',price:'179 Kč'},
{data:'2018-11-23',name:'Fried Rice',desc:'Pražená rýže s drůbežím masem, zeleninou a žampiony, sázené vejce, smažená cibulka, kyselá okurka.',price:'169 Kč'},
{data:'2018-11-23',name:'Nás hovězí guláš',desc:'Dušený hovězí krk s cibulí a červenou paprikou, domácí špecle, mrkev s rozinkami.',price:'179 Kč'},
{data:'2018-11-21',name:'Hovězí na česneku',desc:'Dušený hovězí krk, naše bramborové knedlíky, krémový špenát, smažená vídeňská cibulka.',price:'189 Kč'},
{data:'2018-11-20',name:'Konfitované kachní stehno',desc:'Pomalu pečené kachní stehno v sádle, naše houskové knedlíky, vinné červené zelí, vídeňská cibulka.',price:'199 Kč'},
{data:'2018-11-19',name:'Smažené nugety z lososa',desc:'Mléčná bramborová kaše, míchaný zeleninový salát.',price:'179 Kč'},
{data:'2018-11-16',name:'"Hovězí na smetaně zvaná ""svíčková"""',desc:'Vyzrálá uruguayská kýta, naše houskové knedlíky, citron, brusinky.',price:'209 Kč'},
{data:'2018-11-16',name:'Telecí na houbách',desc:'Dušené telecí maso v delikátní smetanové omáčce s lesními houbami, naše houskové knedlíky.',price:'179 Kč'},
{data:'2018-11-14',name:'Pečená husa',desc:'Pomalu pečená husa s jablky, bramborové nebo houskové knedlíky, vinné červené zelí, přírodní šťáva.',price:'249 Kč'},
{data:'2018-11-06',name:'Telecí na paprice',desc:'Dušená telecí kýta na paprice s bílým vínem a smetanou, naše špecle.',price:'169 Kč'},
{data:'2018-11-02',name:'Řízek z krkovice',desc:'V trojobalu dozlatova smažený řízek z libové krkovice, náš bramborový salát, citron.',price:'189 Kč'},
{data:'2018-11-01',name:'Tori Teriyaki',desc:'Vykostěné kuřecí stehno s Teriyaki omáčkou (sojová omáčka, bílé víno), dušená mrkev a brokolice, jasmínová rýže. Populární japonské jídlo.',price:'179 Kč'},
{data:'2018-11-01',name:'Tori Teriyaki',desc:'Vykostěné kuřecí stehno s Teriyaki omáčkou (sojová omáčka, bílé víno), dušená mrkev a brokolice, jasmínová rýže.',price:'179 Kč'},
{data:'2018-10-31',name:'Mexické Tacos',desc:'Kukuřičné Tacos Shells plněné mletým hovězím masem, sýrem, ledovým salátem a rajčaty, česnekový dresing, hranolky, mexická česneková salsa.',price:'169 Kč'},
{data:'2018-10-31',name:'Pečené mladé divoké prase',desc:'Pomalu pečené sele divokého prasete, naše houskové knedlíky, kysané zelí.',price:'189 Kč'},
{data:'2018-10-30',name:'Mexické Tacos',desc:'Kukuřičné Tacos Shells plněné mletým hovězím masem, sýrem, ledovým salátem a rajčaty, česnekový dresing, hranolky, mexická rajčatová salsa.',price:'169 Kč'},
{data:'2018-10-29',name:'Pečené mladé divoké prase',desc:'Pomalu pečené sele divokého prasete, bramborové noky, kysané zelí.',price:'189 Kč'},
{data:'2018-10-26',name:'Hovězí guláš',desc:'Na kostky krájený, dušený hovězí krk, naše houskové knedlíky, mrkev s rozinkami.',price:'189 Kč'},
{data:'2018-10-25',name:'Grilovaný Steak Salisbury',desc:'Steak z mletého hovězího v delikátní omáčce Diane s červeným vínem a žampiony, šťouchané brambory, kukuřice O\'Brien.',price:'189 Kč'},
{data:'2018-10-24',name:'Kuře na paprice',desc:'V delikátní smetanové omáčce s červenou paprikou, naše špecle.',price:'179 Kč'},
{data:'2018-10-23',name:'Smažený telecí karbanátek',desc:'Telecí maso s provensálským kořením, mléčná bramborová kaše, míchaný zeleninový salát.',price:'179 Kč'},
{data:'2018-10-22',name:'BBQ vepřová žebírka',desc:'Vepřová žebírka pečená v BBQ omáčce, crispers hranolky, coleslaw.',price:'169 Kč'},
{data:'2018-10-21',name:'Hovězí po Burgundsku',desc:'Vyzrálý irský hovězí krk dušený s červeným vínem, kořenovou zeleninou a rozmarýnem, žampiony, stříbrné cibulky, mléčná bramborová kaše.',price:'229 Kč'},
{data:'2018-10-18',name:'Pečené kuře na másle',desc:'Na másle pečené zlaté kuře, dýňové pyré, nádivka s domácím uzeným, šťouchané brambory.',price:'189 Kč'},
{data:'2018-10-17',name:'Duck Fried Rice',desc:'Pražená rýže s kachním masem, zeleninou a žampiony, sázené vejce, kyselá okurka, smažená cibulka.',price:'179 Kč'},
{data:'2018-10-17',name:'Smažené rybí karbanátky',desc:'Mletý čerstvý losos, petrželka, smažená cibulka se slaninou, v trojobalu smažené dozlatova, mléčná bramborová kaše, míchaný salát.',price:'189 Kč'},
{data:'2018-10-15',name:'Beef Stroganoff',desc:'Hovězí kýta krájená na nudličky v delikátní smetanové omáčce se žampiony a kyselou okurkou, jasmínová rýže.',price:'189 Kč'},
{data:'2018-10-15',name:'Beef Stroganoff',desc:'Hovězí kýta krájená na nudličky v delikátní smetanové omáčce se žampiony a kyselou okurkou, rýže Parboiled.',price:'189 Kč'},
{data:'2018-10-12',name:'Smažená treska',desc:'Ve vinném těstíčku, crispers brambory, tatarská omáčka.',price:'189 Kč'},
{data:'2018-10-11',name:'Maďarský guláš',desc:'Pomalu dušený hovězí krk, naše houskové knedlíky, cibule.',price:'179 Kč'},
{data:'2018-10-10',name:'Telecí na lesních houbách',desc:'Telecí kýta, hřibovité houby, jasmínová rýže.',price:'189 Kč'},
{data:'2018-10-10',name:'Telecí na lesních houbách',desc:'Telecí kýta, hřibovité houby, náš karlovarský knedlík.',price:'189 Kč'},
{data:'2018-10-09',name:'Kachní prsa Teriyaki',desc:'Na kousky krájená kachní prsa, pórek, paprika, japonská omáčka Teriyaki, jasmínová rýže.',price:'189 Kč'},
{data:'2018-10-05',name:'Pfeffer steak',desc:'Populární americké jídlo. Tenké plátky z vyzrálé uruguayské kýty v delikátní pepřové omáčce se zeleninou, dušená rýže parboiled.',price:'199 Kč'},
{data:'2018-10-04',name:'Losos Coulibiac',desc:'Steak z lososa zabalený a pečený v listovém těstě se směsí žampiónů, cibule, česneku, petrželky a rýže. Šťouchané brambory se slaninou, náš krémový špenát.',price:'219 Kč'},
{data:'2018-10-04',name:'Roastbeef',desc:'Při nízké teplotě dorůžova pečený vyzrálý uruguayský roštěnec, restované brambory s cibulí, naše tatarská omáčka, přírodní šťáva.',price:'219 Kč'},
{data:'2018-10-03',name:'Geschnetzeltes - Švýcarská specialita',desc:'Na nudličky krájená vepřová panenka v delikátní smetanové omáčce se žampiony, bílým vínem a bramborové rösti.',price:'189 Kč'},
{data:'2018-10-02',name:'Geschnetzeltes',desc:'Delikátní smetanová omáčka se žampiony a bílým vínem, bramborové rösti.',price:'189 Kč'},
{data:'2018-10-02',name:'Geschnetzeltes',desc:'Delikátní smetanová omáčka se žampiony a bílým vínem.',price:'189 Kč'},
{data:'2018-10-01',name:'Pečený králík na cibulce a slanině',desc:'Králík z domácího chovu, kysané zelí, naše bramborové knedlíky a smažená cibulka.',price:'199 Kč'},
{data:'2018-09-28',name:'Beef stroganoff',desc:'Na nudličky krájený vyzrálý hovězí ořech ve smetanové omáčce se zakysanou smetanou, okurkou a hranolky.',price:'209 Kč'},
{data:'2018-09-28',name:'Kuřecí stehno na paprice',desc:'V delikátní smetanové omáčce, naše špecle.',price:'179 Kč'},
{data:'2018-09-26',name:'BBQ trhané vepřové',desc:'Pomalu pečená vepřová plec, mléčná bramborová kaše, míchaný zeleninový salát.',price:'189 Kč'},
{data:'2018-09-26',name:'Pečené mladé hovězí',desc:'Pomalu pečené hovězí s kouřovým aromatem z naší pece, přírodní šťáva, mléčná bramborová kaše, míchaný zeleninový salát.',price:'189 Kč'},
{data:'2018-09-21',name:'Grilovaný vepřový steak',desc:'Z vepřové pečeně, omáčka Diane, šťouchané brambory, dýňové pyré.',price:'199 Kč'},
{data:'2018-09-21',name:'Hovězí na houbách',desc:'Hovězí krk v delikátní smetanové omáčce s lesními houbami, naše karlovarské knedlíky.',price:'199 Kč'},
{data:'2018-09-19',name:'Fried Rice',desc:'Pražená rýže s lososem a chobotnicí, zelenina, kyselá okurka, sázené vejce, smažená cibulka.',price:'219 Kč'},
{data:'2018-09-18',name:'Karlovarský guláš',desc:'Z vyzrálé uruguayské hovězí kýty, karlovarské knedlíky.',price:'189 Kč'},
{data:'2018-09-18',name:'Pečené farmářské kuře',desc:'Pomalu pečené v naší unikátní peci na dřevě s kouřovým aromatem, šťouchané brambory, míchaný zeleninový salát.',price:'159 Kč'},
{data:'2018-09-17',name:'Pečené farmářské kuře',desc:'Pomalu pečené v naší unikátní peci na dřevě s kouřovým aromatem, mléčná bramborová kaše, míchaný zeleninový salát.',price:'189 Kč'},
{data:'2018-09-14',name:'Těstoviny s lososem',desc:'Těstoviny tagliatelle v krémové smetanové omáčce s kousky lososa a mladého hrášku.',price:'179 Kč'},
{data:'2018-09-13',name:'Pečená krkovice',desc:'Pomalu pečená v naší unikátní peci na dřevě s kouřovým aromatem, naše bramborové knedlíky, krémový špenát, smažená cibulka.',price:'179 Kč'},
{data:'2018-09-11',name:'Králík na smetaně',desc:'Zvaná svíčková, náš karlovarský knedlík, citron, brusinky.',price:'199 Kč'},
{data:'2018-09-11',name:'Pečená krkovice z naší unikátní pece s kouřovým aromatem',desc:'Naše bramborové knedlíky s vídeňskou cibulkou, krémový špenát.',price:'179 Kč'},
{data:'2018-09-07',name:'Chicken Burger',desc:'V trojobalu dozlatova smažený kuřecí řízek v bulce, majonézový dip, ledový salát, hranolky, rajčatový salát s baby špenátem.',price:'189 Kč'},
{data:'2018-09-07',name:'Smažený kuřecí řízek v bramborovo-pšeničné bulce',desc:'Majonézový dip, ledový salát, hranolky, rajčatový salát s baby špenátem.',price:'189 Kč'},
{data:'2018-09-06',name:'Smažený kuřecí řízek v bramborovo-pšeničné bulce',desc:'Majonézový dip, ledový salát, hranolky, rajčatový salát s baby špenátem..',price:'189 Kč'},
{data:'2018-09-06',name:'Smažený kuřecí řízek v sezamové bulce',desc:'Majonézový dip, ledový salát, hranolky, rajčatový salát s baby špenátem.',price:'189 Kč'},
{data:'2018-09-05',name:'Rožněná hovězí kýta',desc:'Na bukovém dřevě, lahůdkové brambory, krémový špenát, hovězí kýta z mladého býka z českého chovu.',price:'219 Kč'},
{data:'2018-09-04',name:'Vepřová žebra',desc:'Pečená v BBQ omáčce, hranolky, Coleslaw.',price:'179 Kč'},
{data:'2018-09-03',name:'Hovězí na houbách',desc:'Irský Chuck Roll, lesní houby, jasmínová rýže, máslový hrášek.',price:'189 Kč'},
{data:'2018-08-30',name:'Grilovaný steak z vepřové pečeně',desc:'Lahůdkové brambory restované na másle, krémový špenát, pepřová omáčka.',price:'179 Kč'},
{data:'2018-08-29',name:'Segedínský guláš (Székely gulyás)',desc:'Krájená vepřová plec ve smetanové omáčce s kysaným zelím, červenou paprikou a náš houskový knedlík.',price:'169 Kč'},
{data:'2018-08-29',name:'Smažený krůtí řízek',desc:'V trojobalu se sezamovými semínky dozlatova smažené, mléčná bramborová kaše, kyselá okurka.',price:'189 Kč'},
{data:'2018-08-23',name:'Beef Stew',desc:'Hovězí maso, mrkev, řapíkatý celer, cibule, hrášek, vařené brambory.',price:'179 Kč'},
{data:'2018-08-21',name:'Pečené telecí',desc:'Pomalu pečené telecí s kouřovým aromatem, vařené lahůdkové brambory, krémový špenát, přírodní šťáva.',price:'199 Kč'},
{data:'2018-08-20',name:'Hovězí na česneku',desc:'Stařený irský Chuck Roll, naše bramborové knedlíky, krémový špenát, smažená cibulka.',price:'189 Kč'},
{data:'2018-08-16',name:'Řízek z krkovice',desc:'V trojobalu dozlatova smažený řízek z vepřové krkovice, letní bramborový salát.',price:'199 Kč'},
{data:'2018-08-15',name:'Hovězí na smetaně',desc:'Zvané svíčková, stařená falešná svíčková, karlovarské knedlíky, citron, brusinky.',price:'189 Kč'},
{data:'2018-08-14',name:'Pečená plněná paprika',desc:'S mletým hovězím a vepřovým masem, jasmínová rýže.',price:'169 Kč'},
{data:'2018-08-14',name:'Pečená plněná paprika',desc:'S mletým hovězím a vepřovým masem, rajskou omáčkou, jasmínová rýže.',price:'169 Kč'},
{data:'2018-08-13',name:'Trhané vepřové',desc:'Pomalu pečené vepřové v naší unikátní peci na dřevě s kouřovým aromatem, mléčná bramborová kaše, smažená cibulka, míchaný salát.',price:'169 Kč'},
{data:'2018-08-12',name:'Jemný telecí guláš',desc:'Delikátní smetanová omáčka s bílým vínem a paprikou, jasmínová rýže.',price:'179 Kč'},
{data:'2018-08-10',name:'Jemný telecí guláš',desc:'S paprikou, bílým vínem a smetanou.',price:'179 Kč'},
{data:'2018-08-09',name:'Grilovaný Flap Steak',desc:'Uruguayský hovězí pupek sous vide, šťouchané brambory, krémový špenát, delikátní omáčka Diane s červeným vínem a žampiony.',price:'199 Kč'},
{data:'2018-08-07',name:'Smažené nugety z lososa',desc:'Mléčná bramborová kaše s baby špenátem, míchaný salát.',price:'189 Kč'},
{data:'2018-08-06',name:'Bramborové noky',desc:'S lososem a baby špenátem ve smetanové omáčce.',price:'189 Kč'},
{data:'2018-08-06',name:'Hovězí krk',desc:'Vyzrálý uruguayský Chuck Roll pečený několik hodin v naší unikátní peci na tvrdém dřevě s kouřovým aroma, bramborové noky, krémový špenát, au jus.',price:'209 Kč'},
{data:'2018-08-06',name:'Hovězí krk',desc:'Vyzrálý uruguayský Chuck Roll pečený několik hodin v naší unikátní peci na tvrdém dřevě s kouřovým aromatem, bramborové noky, krémový špenát, au jus.',price:'209 Kč'},
{data:'2018-08-04',name:'Duck Fried Rice',desc:'Pražená rýže s kachním masem a zeleninou, smažená cibulka, kyselá okurka, sázené vejce.',price:'169 Kč'},
{data:'2018-08-02',name:'Pečené farmářské kuře',desc:'Kuře z farmy U Jelena, pečené několik hodin na tvrdém dřevě s kouřovým aroma, mléčná bramborová kaše, míchaný zeleninový salát.',price:'169 Kč'},
{data:'2018-08-02',name:'Pečené farmářské kuře',desc:'Kuře z farmy U Jelena, pečené několik hodin na tvrdém dřevě s kouřovým aromatem, mléčná bramborová kaše, míchaný zeleninový salát.',price:'169 Kč'},
{data:'2018-07-31',name:'Hamburská vepřová pečeně na smetaně',desc:'Na nudličky krájená burgundská šunka a kyselá okurka, naše karlovarské knedlíky.',price:'179 Kč'},
{data:'2018-07-31',name:'Vepřová pečeně na smetaně',desc:'Náš karlovarský knedlík, citrón, brusinky.',price:'179 Kč'},
{data:'2018-07-30',name:'Kančí kýta na smetaně',desc:'Náš karlovarský knedlík, citrón, brusinky.',price:'189 Kč'},
{data:'2018-07-26',name:'Pečený hovězí krk',desc:'Vyzrálý chuck roll pomalu pečený v naší unikátní peci na dřevě s kouřovým aroma, lahůdkové brambory, krémový špenát, au jus.',price:'189 Kč'},
{data:'2018-07-25',name:'Chuck Roll',desc:'Vyzrálý uruguayský krk, lahůdkové brambory, krémový špenát, au jus.',price:'189 Kč'},
{data:'2018-07-24',name:'Telecí na divokých houbách',desc:'Rýže parboiled, máslový hrášek.',price:'189 Kč'},
{data:'2018-07-19',name:'Smažený telecí karbanátek',desc:'Mléčná bramborová kaše, malý Caesar salát.',price:'179 Kč'},
{data:'2018-07-18',name:'Brisket burger',desc:'Uruguyaské stařené hovězí hrudí naložené ve směsi koření, pomalu pečené v naší unikátní peci na tvrdém dřevě s kouřovým aroma v sezamové bulce, ledový salát, česnekový dip, Coleslaw.',price:'189 Kč'},
{data:'2018-07-17',name:'Konfitované kachní stehno',desc:'Mléčná bramborová kaše, míchaný zeleninový salát.',price:'189 Kč'},
{data:'2018-07-11',name:'Pomalu pečené zadní koleno',desc:'Na černém pivě a zelenině, jihočeská lepenice (bramborová kaše s kysaným zelím a smaženou cibulkou).',price:'179 Kč'},
{data:'2018-07-10',name:'Hovězí na smetaně zvané svíčková',desc:'Hovězí uruguayská kýta, naše karlovarské knedlíky, citron, brusinky.',price:'189 Kč'},
{data:'2018-07-10',name:'Pomalu pečené zadní koleno',desc:'Na černém pivě a zelenině, mléčná bramborová kaše, míchaný zeleninový salát.',price:'189 Kč'},
{data:'2018-07-09',name:'Hovězí na smetaně zvané svíčková',desc:'Hovězí uruguayská kýta, náš karlovarský knedlík, brusinky, citrón.',price:'189 Kč'},
{data:'2018-07-05',name:'Pomalu pečená krkovice',desc:'V naší unikátní peci s kouřovým aroma, bramborové špalíčky, krémový špenát, smažená cibulka.',price:'199 Kč'},
{data:'2018-07-05',name:'Pomalu pečená krkovice',desc:'V naší unikátní peci s kouřovým aromatem, bramborové špalíčky, krémový špenát, smažená cibulka.',price:'199 Kč'},
{data:'2018-07-02',name:'Pečený králík a vepřový bok',desc:'S kořenovou zeleninou a bílým vínem, naše bramborové knedlíky, kyselé zelí, smažená cibulka.',price:'189 Kč'},
{data:'2018-06-29',name:'Fried Rice',desc:'Pražená rýže s krůtím masem, zeleninou, žampiony, sázené vejce, smažená cibulka, kyselá okurka.',price:'159 Kč'},
{data:'2018-06-28',name:'Beef Picadillo',desc:'Mexická specialita z mletého hovězího masa, cibule, drcených rajčat a oliv, jasmínová rýže.',price:'169 Kč'},
{data:'2018-06-27',name:'Rožněné divoké prase',desc:'Lahůdkové brambory, salát z kysaného zelí, hořčice.',price:'179 Kč'},
{data:'2018-06-26',name:'Vepřový guláš',desc:'Pomalu dušená vepřová plec, jasmínová rýže.',price:'179 Kč'},
{data:'2018-06-25',name:'Hovězí po Burgundsku',desc:'Dušená uruguayská kýta na červeném víně s mrkví, cibulkami a žampiony, mléčná bramborová kaše.',price:'189 Kč'},
{data:'2018-06-23',name:'Hovězí po burgundsku',desc:'Dušená, stařená uruguayská kýta na červeném víně s mrkví, cibulkami a žampiony, mléčná bramborová kaše s medvědím česnekem.',price:'219 Kč'},
{data:'2018-06-21',name:'Cod filet',desc:'Filet z tresky tmavé, pečený na másle, mléčná bramborová kaše s jarní cibulkou a oříškovým máslem, malý caesar salát.',price:'189 Kč'},
{data:'2018-06-20',name:'Pečená krůta',desc:'Pečená v naší unikátní peci s kouřovým aroma, naše bramborové knedlíky, krémový špenát, smažená cibulka.',price:'189 Kč'},
{data:'2018-06-19',name:'Telecí na smetaně',desc:'Naše karlovarské knedlíky, citron, brusinky.',price:'199 Kč'},
{data:'2018-06-14',name:'Pečená selečí roláda',desc:'Mléčná bramborová kaše, míchaný salát.',price:'179 Kč'},
{data:'2018-06-13',name:'Vepřová krkovice',desc:'Pomalu pečená v naší unikátní peci na tvrdém dřevě s kouřovým aroma, naše bramborové knedlíky, krémový špenát, smažená cibulka.',price:'189 Kč'},
{data:'2018-06-12',name:'Vepřová krkovice',desc:'Pomalu pečená v naší unikátní peci na tvrdém dřevě s kouřovým aroma, naše bramborové knedlíky, krémový špenát, smažená cibulka',price:'189 Kč'},
{data:'2018-06-07',name:'Krůtí prso sous-vide',desc:'Mléčná bramborová kaše, delikátní jablečná omáčka, brokolice.',price:'189 Kč'},
{data:'2018-06-03',name:'Telecí kýta na paprice',desc:'Delikátní smetanová omáčka s paprikou, naše houskové knedlíky.',price:'179 Kč'},
{data:'2018-06-01',name:'Telecí kýta na paprice',desc:'delikátní smetanová omáčka s paprikou, naše houskové knedlíky',price:'179 Kč'},
]},
{name:'nabidka-polevka',data:[
{data:'2019-10-18',name:'Lososový krém',desc:'Krémová polévka s kousky lososa a hráškem.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-10-18',name:'Boršč',desc:'Hovězí maso, slanina, kořenová zelenina, zelí, rajčata, červená řepa, zakysaná smetana.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-10-17',name:'Kuřecí krémová polévka',desc:'S kuřecím masem, hráškem a smetanou.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-10-15',name:'Dršťková polévka',desc:'Taková jaká má být, plná hovězích drštěk.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-10-11',name:'Hrstková polévka',desc:'Fazole, čočka, hrášek, klobása, česnek, majoránka.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-10-11',name:'Couračka',desc:'Tradiční česká polévka z kysaného zelí, smetany a brambor.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-10-09',name:'Jihočeská kulajda',desc:'S lesními houbami a ztraceným vejcem.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-10-08',name:'Mrkvový krém',desc:'Americká specialita, smetana, strouhaná mrkev, citronová šťáva.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-10-04',name:'Gulášová',desc:'Taková jaká má být, s kousky hovězího masa.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-10-03',name:'Saint-Germain',desc:'Populární francouzská polévka z čerstvého hrášku, máslové krutony.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-10-01',name:'Zelňačka',desc:'S klobásou a slaninou.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-10-01',name:'Saint-Germain',desc:'Populární francouzská polévka z hrášku, máslové krutony.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-09-27',name:'Dýňová polévka',desc:'Máslové krutony, opražená dýňová semínka.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-09-26',name:'Jitrnicová polévka',desc:'Prejt, smažená cibulka, vepřové játra, česnek, majoránka, nové koření, kroupy.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-09-25',name:'Tomatový krém',desc:'Krémová polévka z rajčat, bešamelu a smetany s máslovými krutony.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-09-20',name:'Králičí kaldoun',desc:'Králičí vývar zahuštěný máslovou jíškou s kořenovou zeleninou, masem a nočky.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-09-20',name:'Pražská bramborová polévka',desc:'Kořenová zelenina, brambory a šunka.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-09-17',name:'Česnečka',desc:'S vejcem a brambory, chlebové krutony.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-09-16',name:'Květáková polévka',desc:'Tradiční česká polévka z květáku a smetany.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-09-13',name:'Bramborová polévka',desc:'S lesními houbami.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-09-11',name:'Čočková polévka',desc:'S klobásou.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-09-09',name:'Mexický česnekový krém',desc:'S máslovými krutony.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-09-06',name:'Dršťková polévka',desc:'Taková, jaká má být, plná hovězích drštěk.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-09-05',name:'Gulášová polévka',desc:'Taková, jaká má být, s kousky hovězího masa.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-09-03',name:'Kuřecí vývar',desc:'S masem, zeleninou a nudlemi.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-08-30',name:'Zeleninová polévka',desc:'Polévka z mrkve, pórku, hrášku a kukuřice zahuštěná máslovou jíškou a zjemněná smetanou.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-08-30',name:'Zeleninová polévka',desc:'Polévka z mrkve, pórku, hrášku, kukuřice, brambor, cibule, červené papriky a bílého zelí zahuštěná máslovou jíškou a zjemněná smetanou.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-08-29',name:'Frankfurtská polévka',desc:'Červená paprika, brambory, párek, smetana.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-08-26',name:'Fazolová polévka',desc:'Tradiční česká polévka s fazolemi a klobásou.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-08-23',name:'Brokolicový krém',desc:'Máslové krutony.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-08-22',name:'Brokolicový krém',desc:'S máslovými krutony.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-08-20',name:'Kuřecí vývar',desc:'S masem, nudlemi a zeleninou.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-08-19',name:'Blatenská bramborová polévka',desc:'Brambory, kořenová zelenina, slanina, krupice, česnek, pórek, vejce.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-08-14',name:'Tomatový krém',desc:'S máslovými krutony.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-08-09',name:'Zelňačka',desc:'S uzeninou (klobása, slanina, špekáček).',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-08-06',name:'Ukrajinský boršč',desc:'Hovězí maso, kořenová zelenina, červená řepa, brambory, cibule, zakysaná smetana.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-08-02',name:'Králičí kaldoun',desc:'Podřipská specialita, králičí vývar s libečkem zahuštěný máslovou jíškou, drůbky, maso, zelenina a těstoviny.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-08-01',name:'Jihočeská kulajda',desc:'Krémová polévka s lesními houbami, brambory, koprem a zastřeným vejcem.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-07-29',name:'Krém z medvědího česneku',desc:'Máslové krutóny.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-07-26',name:'Zelňačka s klobásou',desc:'Kysané zelí, brambory, smetana.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-07-25',name:'Česnečka',desc:'S hovězím masem, zeleninou, bramborami a chlebovými krutony.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-07-23',name:'Fisherman’s Chowder',desc:'Populární americká rybí polévka s mrkví a hráškem.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-07-22',name:'Fisherman’s Chowder',desc:'Populární americká polévka s mrkví a hráškem.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-07-17',name:'Vichyssoise',desc:'Francouzská polévka z pórku, brambor a smetany.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-07-12',name:'Saint-Germain',desc:'Populární krémová polévka z hrášku, máslové krutony.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-07-12',name:'Saint- Germain',desc:'Populární krémová polévka z hrášku, máslové krutony.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-07-11',name:'Šumavská bramboračka',desc:'S lesními houbami.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-07-09',name:'Bramboračka',desc:'Kořenová zelenina, brambory, lesní houby.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-07-04',name:'Kuřecí vývar',desc:'S kousky kuřecího masa, zeleninou a tenkými nudlemi.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-06-26',name:'Krém z medvědího česneku',desc:'Smetanová polévka s máslovými krutony.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-06-20',name:'Květáková polévka',desc:'Tradiční česká polévka z květáku, smetany a naše malé noky.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-06-20',name:'Květáková polévka',desc:'S nočky.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-06-19',name:'Kukuřičný Chowder',desc:'Americká kukuřičná krémová polévka se slaninou, červenou a zelenou paprikou zjemněná smetanou.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-06-14',name:'Zelňačka',desc:'S klobásou.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-06-13',name:'Gulášová polévka',desc:'Taková jaká má být, s kousky hovězího masa.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-06-11',name:'Zeleninová polévka',desc:'Brambory, kukuřice, pórek, mrkev, smetana a máslová jíška.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-06-07',name:'Frankfurtská polévka',desc:'Brambory, párek, smetana, červená paprika.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-06-07',name:'Frankfurtská polévka',desc:'Brambory, párek, smetana, červená paprika..',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-06-06',name:'Česnečka',desc:'S kořenovou zeleninou a vejcem, chlebové krutony opečené na sádle.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-06-04',name:'Bramborová polévka',desc:'Brambory, kořenová zelenina, česnek.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-05-31',name:'Dršťková polévka.',desc:'Taková, jaká má být, plná hovězích drštěk.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-05-29',name:'Kulajda',desc:'Tradiční krémová polévka s lesními houbami, brambory, koprem a zastřeným vejcem.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-05-29',name:'Fazolová polévka',desc:'Bílé fazole, opečená ústecká klobása.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-05-28',name:'Kulajda',desc:'Tradiční krémová polévka lesními houbami, brambory, koprem a zastřeným vejcem.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-05-24',name:'Uzená polévka',desc:'Polévka s rýží, kořenovou zeleninou a uzeným masem.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-05-20',name:'Králičí polévka',desc:'S králičím masem, droby, zeleninou a širokými nudlemi.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-05-18',name:'Chřestová polévka',desc:'Smetanová polévka z bílého a zeleného chřestu.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-05-17',name:'Hráškový krém',desc:'S máslovými krutony.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-05-16',name:'Špenátová polévka',desc:'Krémová polévka ze špenátu, cibule a smetany s máslovými krutony.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-05-15',name:'Smetanová zelňačka',desc:'S uzeným masem a slaninou.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-05-10',name:'Čočková polévka',desc:'S vídeňským párkem.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-05-08',name:'Ukrajinský boršč',desc:'Hovězí maso, kořenová zelenina, zelí, červená řepa, slanina a zakysaná smetana.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-05-04',name:'Bramboračka',desc:'S lesními houbami.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-05-03',name:'Mexický česnekový krém',desc:'Krémová polévka ze smetany a česneku s máslovými krutony.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-05-01',name:'Chřestový krém',desc:'Krémová polévka ze zeleného chřestu.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-04-30',name:'Chřestová polévka',desc:'Krémová polévka ze zeleného chřestu.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-04-26',name:'Špenátový krém',desc:'S máslovými krutony a opečenou slaninou.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-04-24',name:'Zelňačka',desc:'S uzeným masem a slaninou.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-04-22',name:'Čočková moravská polévka',desc:'Hnědá čočka, klobása a jarní cibulka.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-04-22',name:'Scotch Broth',desc:'Skotská polévka ze skopového masa se zeleninou, kroupami a tymiánem.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-04-19',name:'Čočková moravská polévka',desc:'S hnědou čočkou, klobása a jarní cibulka.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-04-17',name:'Brokolicová polévka',desc:'Krémová polévka z brokolice a smetany, máslové krutony.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-04-16',name:'Jihočeská kulajda',desc:'S lesními houbami, brambory a ztraceným vejcem.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2019-04-15',name:'Česnečka',desc:'Chlebové krutony se sýrem.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2018-12-31',name:'Dršťková polévka',desc:'Plná hovězích drštěk, taková jaká má být.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2018-12-19',name:'Čočková polévka',desc:'S hnědou čočkou a párkem.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2018-12-14',name:'Fazolová polévka s klobásou',desc:'Tradiční česká polévka z červených fazolí.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2018-12-06',name:'Kukuřičný Chowder',desc:'Tradiční americká krémová polévka z kukuřice, slaniny a papriky.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2018-11-29',name:'Kozí brada',desc:'Tradiční moravská polévka s kapustou, uzeným masem, brambory a smetanou.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2018-11-28',name:'Kozí brada',desc:'Tradiční moravská polévka s kapustou, klobásou, uzeným masem, brambory a smetanou.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2018-11-23',name:'Gulášová polévka',desc:'Taková, jaká má být, plná hovězího masa.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2018-11-23',name:'Tomatový krém',desc:'Polévka plná rajčat a smetany, máslové krutóny.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2018-11-19',name:'Saint Germain',desc:'Populární krémová polévka z hrášku, máslové krutóny.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2018-11-19',name:'Saint Germain',desc:'Populární polévka z hrášku, máslové krutóny.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2018-11-12',name:'Couračka',desc:'Staročeská polévka z kysaného zelí, brambor a smetany.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2018-11-08',name:'Mexický česnekový krém',desc:'Máslové krutony.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2018-11-05',name:'Italská minestrone',desc:'S hovězím masem a zeleninou.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2018-11-02',name:'Jemná kuřecí polévka',desc:'Kousky kuřecích prsou, mladý hrášek, smetana, máslové krutóny, sypaná čerstvě sekanou petželkou a libečkem.',price:'malá 49 Kč~velká 55 Kč'},
{data:'2018-11-01',name:'Jemná kuřecí polévka',desc:'Kousky kuřecích prsou, mladý hrášek, smetana, máslové krutóny, sypaná čerstvě sekanou petželkou a alibečkem.',price:'malá 43 Kč~velká 49 Kč'},
{data:'2018-10-26',name:'Lososový krém',desc:'Smetanová polévka s kousky lososa a mladým hráškem.',price:'malá 45 Kč~velká 52 Kč'},
{data:'2018-10-25',name:'Hrachová polévka',desc:'S domácím uzeným, krutony z podmáslového chleba.',price:'malá 45 Kč~velká 52 Kč'},
{data:'2018-10-24',name:'Cibulový krém',desc:'Krémová polévka z cibule a smetany, krutony z podmáslového chleba.',price:'malá 45 Kč~velká 52 Kč'},
{data:'2018-10-22',name:'Bramboračka s houbami',desc:'Kořenová zelenina, brambory, lesní houby.',price:'malá 45 Kč~velká 52 Kč'},
{data:'2018-10-16',name:'Moravská kyselice (zelňačka)',desc:'Kysané zelí, klobása, lesní houby, smetana.',price:'malá 45 Kč~velká 52 Kč'},
{data:'2018-10-09',name:'Lososový krém',desc:'Krémová polévka s kousky lososa a mladého hrášku.',price:'malá 45 Kč~velká 52 Kč'},
{data:'2018-10-05',name:'Mexický česnekový krém',desc:'S dozlatova pečenými máslovými krutony.',price:'malá 45 Kč~velká 52 Kč'},
{data:'2018-10-05',name:'Sibiřský boršč',desc:'Hovězí maso, fazole, červená řepa, zakysaná smetana.',price:'malá 45 Kč~velká 52 Kč'},
{data:'2018-10-04',name:'Bramboračka s lesními houbami',desc:'Kořenová zelenina, brambory, hřibovité houby.',price:'malá 45 Kč~velká 52 Kč'},
{data:'2018-10-04',name:'Mexický česnekový krém',desc:'S dozlatova upečenými máslovými krutony.',price:'malá 45 Kč~velká 52 Kč'},
{data:'2018-10-03',name:'Tomatový krém',desc:'Krémová polévka z rajčat, bešamelu, smetany a máslovými krutony.',price:'malá 45 Kč~velká 52 Kč'},
{data:'2018-10-02',name:'Králičí kaldoun',desc:'Bešamelová polévka se zeleninou, králičím masem, široké nudle.',price:'malá 45 Kč~velká 52 Kč'},
{data:'2018-09-28',name:'Dršťková',desc:'Taková, jaká má být, plná hovězích drštěk.',price:'malá 45 Kč~velká 52 Kč'},
{data:'2018-09-27',name:'Kulajda',desc:'S lesními houbami a ztraceným vejcem.',price:'malá 45 Kč~velká 52 Kč'},
{data:'2018-09-26',name:'Kulajda',desc:'S lesními houbami a zastřeným vejcem.',price:'malá 45 Kč~velká 52 Kč'},
{data:'2018-09-22',name:'Čočková polévka',desc:'S uzeným masem.',price:'malá 45 Kč~velká 52 Kč'},
{data:'2018-09-21',name:'Zelňačka',desc:'S naším uzeným.',price:'malá 45 Kč~velká 52 Kč'},
{data:'2018-09-18',name:'Špenátová polévka',desc:'Se zastřeným vejcem.',price:'malá 45 Kč~velká 52 Kč'},
{data:'2018-09-14',name:'Boršč',desc:'Ruská tradiční polévka s hovězím masem, kořeninovou zeleninou a zakysanou smetanou.',price:'malá 45 Kč~velká 52 Kč'},
{data:'2018-09-13',name:'Dýňová polévka',desc:'Podzimní krémová polévka z dýně hokaido se smetanou, posypaná dýňový semínky a zakápnutá dýňovým olejem.',price:'malá 45 Kč~velká 52 Kč'},
{data:'2018-09-07',name:'Kukuřičný chowder',desc:'Americká polévka s kukuřicí a paprikou.',price:'malá 45 Kč~velká 52 Kč'},
{data:'2018-09-04',name:'Kukuřičný Chowder',desc:'Americká krémová polévka s kukuřicí a paprikou.',price:'Malá / velká – 45 Kč / 52 Kč'},
{data:'2018-08-31',name:'Luštěninová polévka',desc:'Směs luštěniny s klobásou.',price:'Malá / velká – 45 Kč / 52 Kč'},
{data:'2018-08-29',name:'Bramboračka s lesními houbami',desc:'Kořenová zelenina, brambory, směs lesních hub.',price:'Malá / velká – 45 Kč / 52 Kč'},
{data:'2018-08-22',name:'Hrášková polévka Saint-Germain',desc:'Populární krémová polévka z čerstvého hrášku, máslové krutony.',price:'Malá / velká – 45 Kč / 52 Kč'},
{data:'2018-08-20',name:'Moravská kulajda',desc:'S lesními houbami a zastřeným vejcem.',price:'Malá / velká – 45 Kč / 52 Kč'},
{data:'2018-08-17',name:'Italská minestra',desc:'Hovězí maso, zelenina, fazole, rajčata, bazalka.',price:'Malá / velká – 45 Kč / 52 Kč'},
{data:'2018-08-14',name:'Italská Minestrone',desc:'Polévka s hovězím masem, zeleninou a fazolemi.',price:'Malá / velká – 45 Kč / 52 Kč'},
{data:'2018-08-14',name:'Květáková',desc:'Česká specialita z polabského květáku a smetany.',price:'Malá / velká – 45 Kč / 52 Kč'},
{data:'2018-08-04',name:'Rajčatový krém',desc:'S máslovými krutony.',price:'Malá / velká – 45 Kč / 52 Kč'},
{data:'2018-08-03',name:'Rajčatový krém',desc:'S máslovými krutóny.',price:'Malá / velká – 45 Kč / 52 Kč'},
{data:'2018-07-31',name:'Hráškový krém Saint-Germain',desc:'Máslové krutony.',price:'Malá / velká – 45 Kč / 52 Kč'},
{data:'2018-07-27',name:'Krém z medvědího česneku',desc:'Máslové krutony.',price:'Malá / velká – 45 Kč / 52 Kč'},
{data:'2018-07-26',name:'Čočková polévka',desc:'S domácí klobásou.',price:'Malá / velká – 45 Kč / 52 Kč'},
{data:'2018-07-23',name:'Králičí vývar',desc:'Drůbky, játrové knedlíčky, zelenina, nudle.',price:'Malá / velká – 45 Kč / 52 Kč'},
{data:'2018-07-20',name:'Fisherman’s Chowder',desc:'Populární americká polévka s kousky ryb a zeleninou.',price:'Malá / velká – 45 Kč / 52 Kč'},
{data:'2018-07-17',name:'Žampionový krém',desc:'S máslovými krutony.',price:'Malá / velká – 45 Kč / 52 Kč'},
{data:'2018-07-09',name:'Dršťková polévka',desc:'Taková jaká má být plná hovězích drštěk.',price:'Malá / velká – 45 Kč / 52 Kč'},
{data:'2018-07-06',name:'Gulášová polévka',desc:'Taková jaká má být s kousky hovězího masa.',price:'Malá / velká – 45 Kč / 52 Kč'},
{data:'2018-07-05',name:'Kulajda',desc:'S lesními houbami a koprem, zastřené vejce.',price:'Malá / velká – 45 Kč / 52 Kč'},
{data:'2018-07-02',name:'Česnečka',desc:'S uzeným masem a kořenovou zeleninou, chlebové krutony, sýr Gouda.',price:'Malá / velká – 45 Kč / 52 Kč'},
{data:'2018-06-27',name:'Kukuřičný Chowder',desc:'Americká národní krémová polévka z kukuřice.',price:'Malá / velká – 45 Kč / 52 Kč'},
{data:'2018-06-25',name:'Kukuřičný Chowder',desc:'Americká národní krémová polévka s kukuřicí.',price:'Malá / velká – 45 Kč / 52 Kč'},
{data:'2018-06-25',name:'Květáková polévka',desc:'Krémová polévka z květáku.',price:'Malá / velká – 45 Kč / 52 Kč'},
{data:'2018-06-22',name:'Saint-Germain',desc:'Francouzská polévka z čerstvého hrášku, máslové krutony.',price:'Malá / velká – 45 Kč / 52 Kč'},
{data:'2018-06-15',name:'Brokolicový krém',desc:'Máslové krutóny.',price:'Malá / velká – 45 Kč / 52 Kč'},
{data:'2018-06-03',name:'Scotch broth',desc:'Skotská polévka ze skopového masa se zeleninou, kroupami a tymiánem',price:'Malá / velká – 43 Kč / 49 Kč'},
]},
{name:'akce-jidlo',data:[
{data:'2019-10-18',name:'Rožněná vepřová kýta',desc:'Na bukovém dřevě s kouřovým aroma, lahůdkové brambory, cibulový salát, hořčice.',price:'229 Kč'},
{data:'2019-10-18',name:'Tatarský steak ze svíčkové 150 g',desc:'Námi míchaný, topinky s česnekem a kapary.',price:'289 Kč'},
{data:'2019-10-16',name:'Pečené telecí',desc:'Telecí maso, lahůdkové brambory s máslem a petrželí, krémový špenát, přírodní šťáva.',price:'259 Kč'},
{data:'2019-10-16',name:'Jablečný štrúdl',desc:'S ořechy, hrozinkami a vanilkovým krémem.',price:'59 Kč'},
{data:'2019-10-09',name:'Štrúdl',desc:'S jablky, ořechy, hrozinkami a vanilkovým krémem.',price:'59 Kč'},
{data:'2019-10-09',name:'Pečená kachna',desc:'Čtvrtka pečené kachny, míchaný zeleninový salát s balkánským sýrem, rozpečený dalamánek.',price:'219 Kč'},
{data:'2019-10-09',name:'Pečená kachna',desc:'Čtvrtka pečené kachny, mléčná bramborová kaše, malý míchaný salát.',price:'229 Kč'},
{data:'2019-10-04',name:'Pečená kachna',desc:'Čtvrtka pečené kachny, mléčná bramborová kaše, malý míchaný salát..',price:'229 Kč'},
{data:'2019-10-02',name:'Pečené hovězí hrudí (brisket)',desc:'Vyzrálé hovězí hrudí z Austrálie (grain fed 140dní), krájené na plátky, podávané s lahůdkovými brambory, brokolice v páře dušená na másle, přírodní šťáva, naše tatarská omáčka.',price:'259 Kč'},
{data:'2019-09-24',name:'Pečená krůta z českého chovu',desc:'Kousky pečené krůty, náš bramborový salát.',price:'219 Kč'},
{data:'2019-09-24',name:'Pečená krůta z českého chovu',desc:'Kousky pečené krůty, mléčná bramborová kaše s baby špenátem, přírodní šťáva.',price:'229 Kč'},
{data:'2019-09-18',name:'Konfitované kachní stehno',desc:'Pomalu pečené maso v kachním sádle, naše bramborové knedlíky, červené vinné zelí, smažená cibulka.',price:'259 Kč'},
{data:'2019-09-11',name:'Tatarský steak ze svíčkové, 150 g',desc:'Námi míchaný, topinky s česnekem a kapary.',price:'289 Kč'},
{data:'2019-09-11',name:'BBQ trhané vepřové v tortile',desc:'Pečené maso, čedar, míchaný salát, česnekový dip, Jalapeňo.',price:'249 Kč'},
{data:'2019-09-11',name:'Trhané vepřové',desc:'S přírodní šťávou, mléčná bramborová kaše, malý míchaný salát.',price:'249 Kč'},
{data:'2019-09-05',name:'Pečené kuře 1',desc:'Čtvrtka pečeného kuřete, míchaný zeleninový salát s balkánským sýrem, rozpečený dalamánek, barbecue dip.',price:'219 Kč'},
{data:'2019-09-05',name:'Pečené kuře 2',desc:'Čtvrtka pečeného kuřete, mléčná bramborová kaše s baby špenátem, přírodní šťáva.',price:'219 Kč'},
{data:'2019-08-29',name:'Pečené kuře',desc:'Čtvrtka pečeného kuřete, míchaný zeleninový salát s balkánským sýrem, rozpečený dalamánek, barbecue dip.',price:'219 Kč'},
{data:'2019-08-29',name:'Pečené kuře',desc:'Čtvrtka pečeného kuřete, mléčná bramborová kaše s baby špenátem, přírodní šťáva.',price:'219 Kč'},
{data:'2019-08-28',name:'Srnčí ragú',desc:'Na kousky krájený váleček z kýty, dušený s liškami a žampiony ve smetanové omáčce z bílého vína, naše špekové knedlíky.',price:'259 Kč'},
{data:'2019-08-22',name:'Hovězí konfitovaná žebra',desc:'Pomalu pečená vyzrálá hovězí žebra s BBQ omáčkou, šťouchané brambory se slaninou a pórkem, česnekový dip.',price:'269 Kč'},
{data:'2019-08-14',name:'Pomalu pečená krůta z českého chovu',desc:'Pečená krůta, míchaný salát, ciabatta s olivami, BBQ dip.',price:'219 Kč'},
{data:'2019-08-14',name:'Pomalu pečená krůta z českého chovu',desc:'Pečená krůta, šťouchané brambory se slaninou a pórkem, krémový špenát, přírodní šťáva.',price:'229 Kč'},
{data:'2019-08-07',name:'Pečené vepřové kolínko',desc:'Pomalu pečené vepřové kolínko na kořenové zelenině a černém pivě, mléčná bramborová kaše s baby špenátem, přírodní šťáva.',price:'239 Kč'},
{data:'2019-07-31',name:'Hovězí konfitovaná žebra',desc:'Pomalu pečená hovězí žebra s BBQ omáčkou, hranolky, kukuřice O’Brien, česnekový dip.',price:'299 Kč'},
{data:'2019-07-26',name:'Trhané vepřové',desc:'S přírodní šťávou, mléčná bramborová kaše s baby špenátem, malý míchaný salát.',price:'249 Kč'},
{data:'2019-07-17',name:'Fajita burger',desc:'V sezamové bulce na nudličky krájená vepřová panenka orestovaná s cibulí, zelenou a červenou paprikou, směsi koření a česneku, ledový salát, česnekový dip, hranolky a jalapeňos papričky.',price:'239 Kč'},
{data:'2019-07-11',name:'Hovězí po burgundsku',desc:'Dušená hovězí líčka na červeném víně s mrkví, cibulkami a žampiony, mléčná bramborová kaše s baby špenátem.',price:'239 Kč'},
{data:'2019-07-04',name:'Rožněné divoké prase',desc:'Pomalu pečené na bukovém dřevě s kouřovým aroma, lahůdkové brambory, pikantní salát z kysaného zelí, hořčice.',price:'150g / 239 Kč'},
{data:'2019-06-25',name:'Pečené zlaté kuře',desc:'Půlka pečeného kuřete, šťouchané brambory s pórkem a slaninou, kukuřice O’Brien.',price:'229 Kč'},
{data:'2019-06-20',name:'Míchaný zeleninový salát s grilovaným steakem z tuňáka žlutoploutvého',desc:'Směs listových salátů, rajčat, okurky, ředkviček a sladké kukuřice, fajita dresink.',price:'249 Kč'},
{data:'2019-06-13',name:'Trhané vepřové',desc:'S přírodní šťávou, bramborová kaše s petrželovým pestem a baby špenátem, malý míchaný salát.',price:'249 Kč'},
{data:'2019-06-12',name:'Trhané vepřové',desc:'S přírodní šťávou, bramborová kaše s petrželovým pestem a baby špenátem, malý míchaný salát..',price:'249 Kč'},
{data:'2019-06-05',name:'Pečené vepřové paličky',desc:'Marinovaná část vepřového kolena s kostí, pečené s cibulí a česnekem, mléčná bramborová kaše, míchaný zeleninový salát.',price:'239 Kč'},
{data:'2019-06-03',name:'Tatarský steak ze svíčkové, 150 g',desc:'Námi míchaný, topinky s česnekem.',price:'289 Kč'},
{data:'2019-05-29',name:'Maďarská pečená kachna s jablky',desc:'Čtvrtka pomalu pečené, částečné vykostěné mladé kachny, náš bramborový knedlík, smažená cibulka, červené vinné zelí.',price:'239 Kč'},
{data:'2019-05-22',name:'Beef Stroganoff',desc:'Na nudličky krájená vyzrálá australská hovězí kýta, dušená v delikátní smetanové omáčce se žampiony a kyselou okurkou, šťouchané brambory, blanšírovaná brokolice.',price:'239 Kč'},
{data:'2019-05-16',name:'BBQ trhané hovězí v sezamové bulce',desc:'Pomalu pečená hovězí kýta, česnekový dip, ledový salát, batátové hranolky, coleslaw.',price:'239 Kč'},
{data:'2019-05-16',name:'Jarní salát',desc:'Míchaný listový zeleninový salát se zeleným a bílým chřestem a grilovaných sýrem Halloumi.',price:'189 Kč'},
{data:'2019-05-13',name:'Jelen se šípkovou omáčkou',desc:'Jelení dušená kýta v omáčce z kořenové zeleniny, divokého koření, slaniny a šípkového džemu, naše karlovarské knedlíky, citron, brusinky.',price:'249 Kč'},
{data:'2019-05-03',name:'Konfitovaná krkovice',desc:'V bylinkové marinádě, mléčná bramborová kaše s medvědím česnekem, smažená vídeňská cibulka.',price:'229 Kč'},
{data:'2019-04-24',name:'Rožněné jehně',desc:'Na bukovém dřevě s kouřovým aroma, lahůdkové brambory, krémový špenát. Váha je po upečení.',price:'100 g 219 Kč~150 g 269 Kč'},
{data:'2019-04-18',name:'Rožněné jehně',desc:'Na bukovém dřevě s kouřovým aroma, lahůdkové brambory, krémový špenát (100 g, čistá váha po upečení).',price:'219 Kč'},
{data:'2019-04-18',name:'Rožněné jehně',desc:'Na bukovém dřevě s kouřovým aroma, lahůdkové brambory, krémový špenát (150 g, čistá váha po upečení).',price:'269 Kč'},
{data:'2019-04-18',name:'ROŽNĚNÉ JEHNĚ',desc:'Na bukovém dřevě s kouřovým aroma, lahůdkové brambory, krémový špenát.',price:'219 Kč'},
{data:'2019-04-18',name:'Smažené nudle s grilovaným hovězím masem',desc:'Smažené nudle se zeleninou, cibulkou, sypané sezamem, grilovaný vyzrálý uruguayský nízký roštěnec, vejce se zeleninou.',price:'229 Kč'},
{data:'2019-04-18',name:'Karamelizovaný ananas',desc:'Smetanová omáčka s vůní badyánu, skořice, fenyklu a hřebíčku, drobenka z ořechů, karamelizovaný sníh.',price:'79 Kč'},
{data:'2019-04-14',name:'Smažené nudle s grilovaným hovězím masem',desc:'Smažené nudle se zeleninou, cibulkou, sypané sezamem, grilovaný vyzrálý uruguayský nízký roštěnec, vejce se zeleninou..',price:'229 Kč'},
{data:'2018-12-31',name:'Geschnetzeltes',desc:'Švýcarská specialita, na nudličky krájená vepřová panenka v delikátní smetanové omáčce s bílým vínem a žampiony,, smažené bramborové rösti.',price:'199 Kč'},
{data:'2018-12-28',name:'Hovězí na smetaně zvané „svíčková“',desc:'Vyzrálá argentinská falešná svíčková v delikátní omáčce z kořenové zeleniny a smetany s divokým kořením, naše karlovarské knedlíky, citron, brusinky.',price:'209 Kč'},
{data:'2018-12-12',name:'Surf and Turf',desc:'Strip steak z nízké roštěné nejvyšší kvality USDA Prime s argentýnskými červenými krevetami, pyré z černého kořene a pečených brambor, špenělská omáčka.',price:'549 Kč'},
{data:'2018-12-06',name:'Trhané vepřové',desc:'Pomalu přes noc pečená vepřová kýta, mléčná bramborová kaše, přírodní šťáva, míchaný salát.',price:'209 Kč'},
{data:'2018-11-29',name:'Kančí guláš',desc:'Dušené maso z divokého prasete s divokým kořením, červeným vínem a česnekem, naše špekové knedlíky, mrkev s rozinkami.',price:'209 Kč'},
{data:'2018-11-22',name:'Hovězí na smetaně zvané „svíčková“',desc:'Vyzrálá uruguyaská kýta, naše karlovarské knedlíky, citron, brusinky.',price:'209 Kč'},
{data:'2018-11-15',name:'Konfitovaná krkovice',desc:'V sádle pomalu pečená krkovice s kořením a česnekem, máslová bramborová kaše, míchaný salát s balkánským sýrem.',price:'199 Kč'},
{data:'2018-10-31',name:'Muflon pečený na česneku',desc:'Bramborové špalíčky, krémový špenát, vídeňská cibulka.',price:'219 Kč'},
{data:'2018-10-24',name:'Hovězí po Burgundsku',desc:'Vyzrálý irský hovězí krk dušený s červeným vínem, kořenovou zeleninou a rozmarýnem, žampiony, stříbrné cibulky, mléčná bramborová kaše.',price:'229 Kč'},
{data:'2018-10-17',name:'Pečené jehně',desc:'Na kořenové zelenině a česneku, naše bramborové knedlíky, krémový špenát, vídeňská cibulka.',price:'229 Kč'},
{data:'2018-10-11',name:'Králík na smetaně',desc:'Domácí králík z Libochovic, karlovarské knedlíky, citron, brusinky.',price:'209 Kč'},
{data:'2018-10-04',name:'Konfitované kachní stehno',desc:'Naše špekové knedlíky, červené vinné zelí, přírodní šťáva.',price:'219 Kč'},
{data:'2018-09-26',name:'BBQ trhané vepřové v sezamové bulce',desc:'Česnekový dip, čínský zelný salát, hranolky, Jalapeño.',price:'219 Kč'},
{data:'2018-09-19',name:'Pečené farmářské kuře',desc:'Pomalu pečené v naší unikátní peci na dřevě s kouřovým aromatem, mléčná bramborová kaše, míchaný zeleninový salát.',price:'219 Kč'},
{data:'2018-09-13',name:'Vepřová krkovice',desc:'Pečená v naší unikátní peci na bukovém dřevě s kouřovým aromatem, nás bramborový salát.',price:'179 Kč'},
{data:'2018-09-06',name:'Rožněná hovězí kýta',desc:'Na bukovém dřevě, lahůdkové brambory, krémový špenát, hovězí kýta z mladého býka z českého chovu.',price:'219 Kč'},
{data:'2018-09-05',name:'Náš tatarský steak ze svíčkové, 150 g',desc:'Námi míchaný, topinky s česnekem..',price:'289 Kč'},
{data:'2018-08-29',name:'Pečené jehněčí na česneku',desc:'Bramborové noky, krémový špenát, přírodní šťáva.',price:'249 Kč'},
{data:'2018-08-23',name:'Pečené telecí',desc:'Pomalu pečené telecí v naší unikátní peci na dřevě s kouřovým aromatem, vařené lahůdkové brambory, krémový špenát, přírodní šťáva.',price:'249 Kč'},
{data:'2018-08-16',name:'BBQ trhané mladé vepřové v sezamové bulce',desc:'Česnekový drezink, čínský zelný salát, hranolky, Jalapeño.',price:'219 Kč'},
{data:'2018-08-16',name:'Fajita salát',desc:'S grilovaným steakem z tuňáka žlutoplouvého, polovina opečené bagety.',price:'199 Kč'},
{data:'2018-08-16',name:'Pečené mladé vepřové',desc:'Pomalu pečené mladé vepřové v naší unikátní peci na dřevě s kouřovým aromatem, šťouchané brambory, krémový špenát.',price:'219 Kč'},
{data:'2018-08-08',name:'Hovězí krk',desc:'Tence krájený vyzrálý uruguayský Chuck Roll pečený několik hodin v naší unikátní peci na tvrdém dřevě s kouřovým aroma, česnekový dip, dalamánková bageta, míchaný salát.',price:'219 Kč'},
{data:'2018-08-08',name:'Hovězí krk',desc:'Vyzrálý uruguayský Chuck Roll pečený několik hodin v naší unikátní peci na tvrdém dřevě s kouřovým aroma, bramborové noky, krémový špenát, au jus.',price:'229 Kč'},
{data:'2018-08-08',name:'Pečené mladé vepřové',desc:'Pomalu pečené mladé vepřové v naší unikátní peci na dřevě s kouřovým aroma, šťouchané brambory, krémový špenát.',price:'219 Kč'},
{data:'2018-08-08',name:'Thajský salát se smaženými krevetami',desc:'Ledový salát, cherry rajčata, bambusové výhonky, arašídy, drcené chilli, polovina opečené bagety.',price:'199 Kč'},
{data:'2018-08-07',name:'Hovězí krk',desc:'Vyzrálý uruguayský Chuck Roll pečený několik hodin v naší unikátní peci na tvrdém dřevě s kouřovým aromatem, bramborové noky, krémový špenát, au jus.',price:'229 Kč'},
{data:'2018-08-06',name:'Hovězí krk',desc:'Tence krájený vyzrálý uruguayský Chuck Roll pečený několik hodin v naší unikátní peci na tvrdém dřevě s kouřovým aromatem, česnekový dip, dalamánková bageta, míchaný salát.',price:'219 Kč'},
{data:'2018-08-02',name:'Halloumi salát',desc:'Míchaný zeleninový salát s grilovaným sýrem Halloumi, opečená bageta.',price:'219 Kč'},
{data:'2018-08-02',name:'Pečené farmářské kuře, 500 g',desc:'Kuře z farmy U Jelena, pečené několik hodin na tvrdém dřevě s kouřovým aroma, míchaný zeleninový salát, opečená bageta, hořčicový dip.',price:'239 Kč'},
{data:'2018-08-02',name:'Pečené farmářské kuře, 500 g',desc:'Kuře z farmy U Jelena, pečené několik hodin na tvrdém dřevě s kouřovým aroma, mléčná bramborová kaše, míchaný zeleninový salát.',price:'239 Kč'},
{data:'2018-07-26',name:'Chuck Roll',desc:'Tence krájený vyzrálý uruguayský krk, česnekový dip, dalamánková bageta, míchaný salát.',price:'219 Kč'},
{data:'2018-07-26',name:'Chuck Roll',desc:'Vyzrálý uruguayský krk, lahůdkové brambory, krémový špenát, au jus.',price:'229 Kč'},
{data:'2018-07-26',name:'Náš tatarský steak ze svíčkové, 150 g',desc:'Námi míchaný, topinky s česnekemm.',price:'289 Kč'},
{data:'2018-07-26',name:'Thajský salát s grilovaným steakem z tuňáka',desc:'Ledový salát, cherry rajčata, bambusové výhonky, arašídy, drcené chilli, polovina opečené bagety.',price:'199 Kč'},
{data:'2018-07-19',name:'Brisket',desc:'Uruguyaské stařené hovězí hrudí naložené ve směsi koření, pomalu pečené v naší unikátní peci na tvrdém dřevě s kouřovým aroma, dalamánková bageta, česnekový dip, Jalapeño, míchaný salát.',price:'209 Kč'},
{data:'2018-07-19',name:'Chuck Roll',desc:'Vyzrálý uruguayský krk, lahůdkové brambory, krémový špenát, Jus.',price:'229 Kč'},
{data:'2018-07-19',name:'Konfitované kachní stehno',desc:'Mléčná bramborová kaše, míchaný zeleninový salát.',price:'219 Kč'},
{data:'2018-07-19',name:'Thajský salát',desc:'Se smaženými krevetami, polovina opečené bagety s česnekovým máslem.',price:'199 Kč'},
{data:'2018-07-12',name:'Pomalu pečené zadní koleno',desc:'Na černém pivě a zelenině, podmáslový chléb, hořčice, křen, kyselá okurka, Jalapeño papričky, Jus.',price:'259 Kč'},
{data:'2018-07-12',name:'Thajský salát s grilovaným steakem z tuňáka',desc:'Ledový salát, cherry rajčata, bambusové výhonky, arašídy, drcené chilli, polovina opečené bagety s česnekovým máslem.',price:'199 Kč'},
{data:'2018-07-12',name:'Trhané maso z mladého divokého kance',desc:'Mléčná bramborová kaše, míchaný salát.',price:'219 Kč'},
{data:'2018-07-04',name:'Pečená krkovice',desc:'Pomalu pečená v naší unikátní peci na tvrdém dřevě s kouřovým aroma, dalamánek, křen, relish, čínský zelný salát.',price:'199 Kč'},
{data:'2018-07-04',name:'Pečená krkovice',desc:'Pomalu pečená v naší unikátní peci na tvrdém dřevě s kouřovým aroma, náš bramborový salát.',price:'199 Kč'},
{data:'2018-07-04',name:'Steak ze sumce',desc:'Pečený na másle, mléčná bramborová kaše s baby špenátem, čínský zelný salát.',price:'219 Kč'},
{data:'2018-06-28',name:'Hovězí po burgundsku',desc:'Dušená, stařená uruguayská kýta na červeném víně s mrkví, cibulkami a žampiony, mléčná bramborová kaše s medvědím česnekem.',price:'219 Kč'},
{data:'2018-06-28',name:'Polovina pečeného zlatého kuřete',desc:'Pomalu pečené v naší unikátní peci na tvrdém dřevě s kouřovým aroma, ciabatta se smaženou cibulkou, míchaný salát s balkánským sýrem.',price:'199 Kč'},
{data:'2018-06-28',name:'Rožněné divoké prase',desc:'Lahůdkové brambory, hořčice, salát z kysaného zelí.',price:'219 Kč'},
{data:'2018-06-21',name:'Hovězí po burgundsku',desc:'Dušená stařená uruguayská kýta na červeném víně s mrkví, cibulkami a žampiony, mléčná bramborová kaše s medvědím česnekem.',price:'219 Kč'},
{data:'2018-06-20',name:'Pečená krůta v naší unikátní peci',desc:'Ciabatta s olivami, míchaný salát.',price:'199 Kč'},
{data:'2018-06-20',name:'Pečená krůta v naší unikátní peci',desc:'Šťouchané brambory se slaninou a pórkem, krémový špenát.',price:'199 Kč'},
{data:'2018-06-20',name:'Stroganoff',desc:'Uruguayská stařená kýta krájená na nudličky v delikátní smetanové omáčce se žampiony, hranolky.',price:'209 Kč'},
{data:'2018-06-18',name:'Náš tatarský steak ze svíčkové 150g',desc:'Námi míchaný, topinky s česnekem.',price:'289 Kč'},
{data:'2018-06-13',name:'Kančí guláš',desc:'S divokými houbami, naše bramborové knedlíky.',price:'219 Kč'},
{data:'2018-06-13',name:'Pečená vepřová krkovice v dalamánkové bagetě',desc:'Česnekový dip, rukola, baby špenát, rajčata, hranolky, čínský zelný salát.',price:'199 Kč'},
{data:'2018-06-13',name:'Pečená vepřová krkovice',desc:'Pomalu pečená v naší unikátní peci na tvrdém dřevě s kouřovým aroma, nové brambory s pažitkou, ragú z hlívy ústřičné a žampionů s bílým vínem a smetanou.',price:'209 Kč'},
{data:'2018-06-12',name:'Kančí guláš',desc:'S divokými houbami, naše bramborové špalíčky.',price:'219 Kč'},
{data:'2018-06-12',name:'Pečená vepřová krkovice',desc:'Pomalu pečená vepřová krkovice v naší unikátní peci s kouřovým aroma, nové brambory s pažitkou, ragú z hlívy ústřičné a žampionů s bílým vínem a smetanou.',price:'209 Kč'},
{data:'2018-06-03',name:'Burger s BBQ trhaným telecím',desc:'Hořčicový dip, vídeňská cibulka, rajče, ledový salát, hranolky, Coleslaw.',price:'219 Kč'},
{data:'2018-06-03',name:'Pepper steak',desc:'Hovězí uruquayská kýta krájená na tenké plátky v pikantní pepřové omáčce se zeleninou, indiánská rýže.',price:'199 Kč'},
{data:'2018-06-03',name:'Pomalu pečené telecí',desc:'Lahůdkové brambory, Jus, krémový špenát.',price:'219 Kč'},
{data:'2018-06-01',name:'Burger s BBQ trhaným telecím',desc:'hořčicový dip, vídeňská cibulka, rajče, ledový salát, hranolky, Coleslaw',price:'219 Kč'},
{data:'2018-06-01',name:'Náš tatarský steak ze svíčkové 150g',desc:'námi míchaný, topinky s česnekem',price:'289 Kč'},
{data:'2018-06-01',name:'Pepper steak',desc:'hovězí uruquayská kýta krájená na tenké plátky v pikantní pepřové omáčce se zeleninou, indiánská rýže',price:'199 Kč'},
{data:'2018-06-01',name:'Pomalu pečené telecí',desc:'lahůdkové brambory, Jus, krémový špenát',price:'219 Kč'},
]},
{name:'akce-predkrm',data:[
{data:'2019-10-18',name:'Tatarský steak ze svíčkové',desc:'Námi míchaný, topinky s česnekem a kapary.',price:'50 g 129 Kč~150 g 289 Kč'},
{data:'2019-09-24',name:'Tartar z lososa',desc:'Jemně sekaný marinovaný losos, opečená bageta s bylinkovým máslem, malý míchaný salát.',price:'129 Kč'},
{data:'2019-09-18',name:'Marinovaný losos Gravlax',desc:'Podávaný s gravlax omáčkou, salát z rukoly a listových salátů, bageta.',price:'129 Kč'},
{data:'2019-09-11',name:'Tatarský steak ze svíčkové, 50 g',desc:'Námi míchaný, topinky s česnekem a kapary.',price:'129 Kč'},
{data:'2019-07-26',name:'BBQ trhané vepřové v sezamové bulce',desc:'Česnekový dip, čínský zelný salát, hranolky, Jalapeňo.',price:'239 Kč'},
{data:'2019-07-11',name:'Thajský salát se smaženými krevetami',desc:'Ledový salát, cherry rajčata, bambusové výhonky, arašídy, drcené chilli, polovina opečené bagety.',price:'219 Kč'},
{data:'2019-07-04',name:'Míchaný salát s grilovaným steakem z tuňáka žlutoploutvého',desc:'Směs listových salátů, rajčata, okurka, ředkvičky a sladká kukuřice, fajita dresink.',price:'249 Kč'},
{data:'2019-06-25',name:'Pečené zlaté kuře',desc:'Půlka pečeného kuřete, míchaný zeleninový salát, rozpečený dalamánek, barbecue dip.',price:'239 Kč'},
{data:'2019-06-20',name:'Rožněná hovězí kýta z plemene Wagyu',desc:'Na bukovém dřevě s kouřovým aroma, lahůdkové brambory, krémový špenát, přírodní šťáva.',price:'269 Kč'},
{data:'2019-06-13',name:'Trhané vepřové v sezamové bulce',desc:'Česnekový dip, mix salátů, rajče, červená cibulka, hranolky a coleslaw.',price:'239 Kč'},
{data:'2019-05-16',name:'Pomalu pečená hovězí kýta',desc:'Vyzrálá australská hovězí kýta, pošírovaný zelený chřest se sýrovou omáčkou, lahůdkové brambory orestované na másle s pažitkou.',price:'269 Kč'},
{data:'2019-04-18',name:'Pho Bo Tai Lan',desc:'Vietnamská polévka s grilovaným vyzrálým uruguayským nízkým roštěncem, rýžovými nudlemi a bylinkami.',price:'189 Kč'},
{data:'2019-01-23',name:'Roastbeef',desc:'Dorůžova při nízké teplotě pečený vyzrálý uruguayský roštěnec, čerstvý podmáslový chléb, kyselá okurka, tatarská omáčka.',price:'129 Kč'},
{data:'2018-10-24',name:'Roastbeef',desc:'Vyzrálý uruguayský roštěnec pečený při nízké teplotě dorůžova, čerstvý podmáslový chléb, kyselá okurka, tatarská omáčka.',price:'129 Kč'},
{data:'2018-10-17',name:'Roastbeef',desc:'Dorůžova při nízké teplotě pečený  vyzrálý uruguayský roštěnec, čerstvý podmáslový chléb, kyselá okurka, tatarská omáčka.',price:'129 Kč'},
{data:'2018-10-04',name:'Grilovaný uzený sýr pološtiepok z liptova',desc:'Čerstvý podmáslový chléb, brusinky, malý listový salát.',price:'109 Kč'},
{data:'2018-09-26',name:'Míchaný salát se smaženými krevetami',desc:'Listový salát, okurka, paprika, rajče, ředkvičky, fajita dresink.',price:'109 Kč'},
{data:'2018-09-20',name:'Míchaný salát se smaženými krevetami',desc:'Listový salát, okurka, paprika, rajče, ředkvičky, fajita drezink.',price:'109 Kč'},
{data:'2018-08-16',name:'Roastbeef',desc:'Dorůžova při nízké teplotě pečený nízký roštěnec, podmáslový chlém od našeho pekaře, tatarská omáčka, kyselá okurka.',price:'129 Kč'},
{data:'2018-08-08',name:'Grilovaná chapadla z chobotnice',desc:'S olivovým olejem, bazalkou a česnekem, polovina opečené bagety, thajský salát.',price:'199 Kč'},
{data:'2018-08-02',name:'Grilovaná chapadla z chobotnice',desc:'S olivovým olejem, bazalkou a česnekem, opečená bageta, míchaný zeleninový salát.',price:'199 Kč'},
{data:'2018-08-02',name:'Grilovaná chapadla z chobotnice',desc:'S olivovým olejem, bazalkou a česnekem, polovina opečené bageta, thajský salát.',price:'199 Kč'},
{data:'2018-07-26',name:'Tatarák z lososa',desc:'Opečený toast, míchaný salát.',price:'129 Kč'},
{data:'2018-07-19',name:'Roastbeef',desc:'Dorůžova při nízké teplotě pečený nízký roštěnec, podmáslový chléb od našeho pekaře, tatarská omáčka, kyselá okurka.',price:'129 Kč'},
{data:'2018-07-12',name:'Tartar z lososa',desc:'Opečený toast, míchaný salát.',price:'129 Kč'},
{data:'2018-07-04',name:'Grilovaná chapadla z chobotnice',desc:'S olivovým olejem, bazalkou a česnekem, opečená bageta, čínský zelný salát.',price:'179 Kč'},
{data:'2018-06-28',name:'Roláda z lososa',desc:'Míchaný salát.',price:'129 Kč'},
{data:'2018-06-18',name:'Náš tatarský steak ze svíčkové 50g',desc:'Námi míchaný, topinky s česnekem.',price:'129 Kč'},
{data:'2018-06-13',name:'Tartar z uzeného marinovaného lososa',desc:'Opečená bageta s bylinkovým máslem.',price:'129 Kč'},
{data:'2018-06-12',name:'Náš tatarský steak ze svíčkové 50 g',desc:'Námi míchaný, topinky s česnekem.',price:'129 Kč'},
{data:'2018-06-03',name:'Hovězí satay',desc:'Grilovaná uruquayská kýta, thajský salát.',price:'129 Kč'},
{data:'2018-06-01',name:'Hovězí satay',desc:'grilovaná uruquayská kýta, thajský salát',price:'129 Kč'},
{data:'2018-06-01',name:'Náš tatarský steak ze svíčkové 50 g',desc:'námi míchaný, topinky s česnekem',price:'129 Kč'},
]},
{name:'nabidka-pivo',data:[
{data:'2020-02-15',name:'Falkenšten APA 13° (víkendová nabídka)',desc:'Polotmavé speciální pivo svrchně kvašené (American Pale Ale) uvařené ze tří druhů sladu a chmelené americkými odrůdami Amarillo, Cascade a Citra, které kromě výrazné hořkosti zanechávají ve vůni i v chuti znatelné aroma tropického ovoce. Pivo je nefiltrované a nepasterované.',price:'0,3 l 35 Kč~0,5 l 55 Kč'},
{data:'2020-02-12',name:'Falkenšten APA 13°',desc:'Polotmavé speciální pivo svrchně kvašené (American Pale Ale) uvařené ze tří druhů sladu a chmelené americkými odrůdami Amarillo, Cascade a Citra, které kromě výrazné hořkosti zanechávají ve vůni i v chuti znatelné aroma tropického ovoce. Pivo je nefiltrované a nepasterované.',price:'0,3 l 35 Kč~0,5 l 55 Kč'},
{data:'2020-02-03',name:'Falkenštejn Ostroff 12° (víkendová nabídka)',desc:'Polotmavý ležák Ostroff je spodně kvašené pivo českého typu uvařené tradiční technologií z pěti druhů sladu, chmelené odrůdami Sládek a Žatecký poloraný červeňák. Pivo jantarové barvy, které osloví vyvážeností karamelových tónů a jemné hořkosti.',price:'0,3 l 32 Kč~0,5 l 47 Kč'},
{data:'2020-01-28',name:'American Pale Ale 11° (víkendová nabídka)',desc:'Speciální pivo svrchně kvašené (APA) uvařené z několika druhů sladu a kvalitních amerických chmelů, vyvážená sladová chuť s tóny karamele, doplněna citrusovou chmelovou hořkostí.',price:'0,3 l 34 Kč~0,5 l 54 Kč'},
{data:'2020-01-23',name:'Bob\'s Amber Lager 13°',desc:'Polotmavé speciální spodně kvašené pivo uvařené ze tří druhů sladů Plzeňský Swaen, Swaen Munich light a Goldswaen Red a chmelené Žateckým poloraným červeňákem a Premiantem.Pivo má bohatou, plnou chuť s úžasnou barvou.',price:'0,3 l 38 Kč~0,5 l 62 Kč'},
{data:'2020-01-20',name:'Bob\'s Amber Lager 13° (víkendová nabídka)',desc:'Polotmavé speciální spodně kvašené pivo uvařené ze tří druhů sladů Plzeňský Swaen, Swaen Munich light a Goldswaen Red a chmelené Žateckým poloraným červeňákem a Premiantem.Pivo má bohatou, plnou chuť s úžasnou barvou.',price:'0,3 l 38 Kč~0,5 l 62 Kč'},
{data:'2019-12-31',name:'American Pale Ale 11°',desc:'Speciální pivo svrchně kvašené (APA) uvařené z několika druhů sladu a kvalitních chmelů, které kromě jemné hořkosti zanechávají ve vůni i v chuti znatelné aroma tropického ovoce.',price:'0,3 l 34 Kč~0,5 l 54 Kč'},
{data:'2019-12-18',name:'Falkenštejn APA 13° (víkendová nabídka)',desc:'Polotmavé speciální pivo svrchně kvašené (American Pale Ale) uvařené ze tří druhů sladu a chmelené americkými odrůdami Amarillo, Cascade a Citra, které kromě výrazné hořkosti zanechávají ve vůni i v chuti znatelné aroma tropického ovoce. Pivo je nefiltrované a nepasterované.',price:'0,3 l 35 Kč~0,5 l 55 Kč'},
{data:'2019-12-06',name:'Falkenštejn 11° (víkendová nabídka)',desc:'Světlý ležák spodně kvašený uvařené tradiční technologií ze dvou druhů sladu, chmelené odrůdami Harmonie a Žatecký poloraný červeňák. Vyznačuje se zlatavou barvou, čistou vůní a plnou chutí. Pivo je nefiltrované a nepasterované.',price:'0,3 l 28 Kč~0,5 l 43 Kč'},
{data:'2019-12-02',name:'Grifel 14° (víkendová nabídka)',desc:'Limitovaná várka zimního speciálu z regionálního pivovaru Ostravar, připravená v otevřených kádích spilky. Čtrnáctka s vyšší plností, hořkostí a výraznějším sladovým aroma. Uvařená ze světlého a bavorského sladu a chmelená třemi druhy chmele.',price:'0,3 l 29 Kč~0,5 l 44 Kč'},
{data:'2019-11-20',name:'Krahulík 11° (víkendová nabídka)',desc:'Spodně kvašený ležák plzeňského typu vařený dvourmutovým způsobem z nejkvalitnějších moravských sladů, chmelený žateckým poloraným červeňákem.',price:'0,3 l 29 Kč~0,5 l 44 Kč'},
{data:'2019-11-01',name:'Krahulík 12° (víkendová nabídka)',desc:'Spodně kvašený ležák plzeňského typu vařený dvourmutovým způsobem z nejkvalitnějších moravských sladů, chmelený žateckým poloraným červeňákem.',price:'0,3 l 30 Kč~0,5 l 45 Kč'},
{data:'2019-10-29',name:'Benedict Ležák 12° (víkendová nabídka)',desc:'Klasická světlá dvanáctka vyrobená tradičním způsobem vyznačující se plností a silnou, ale jemnou hořkostí.',price:'0,3 l 30 Kč~0,5 l 45 Kč'},
{data:'2019-10-21',name:'Mosaic ALE 12° (víkendová nabídka)',desc:'Svrchně kvašený speciál ve stylu American Pale Ale se vyznačuje jednodruhovým chmelením oblíbeným chmelem Mosaic. Ve vůni intenzivní citrusové, tělo citrusové a lehce sladové tóny.',price:'0,3 l 35 Kč~0,5 l 55 Kč'},
{data:'2019-10-11',name:'Podřipská 11° fresh (víkendová nabídka)',desc:'Světlý ležák plzeňského typu, do kterého je přidán čerstvý zelený chmel, který propůjčuje pivu ještě jemnější chuť a vůni s delším dozníváním hořkosti oproti klasickému ležáku.',price:'0,3 l 27 Kč~0,5 l 42 Kč'},
{data:'2019-10-10',name:'Podřipská 11° fresh (víkendová nabídka)',desc:'Světlý ležák plzeňského typu, do kterého je přidán čerství zelený chmel, který propůjčuje pivu ještě jemnější chuť a vůni s delším dozníváním hořkosti oproti klasickému ležáku.',price:'0,3 l 27 Kč~0,5 l 42 Kč'},
{data:'2019-10-09',name:'Podřipská 11° fresh',desc:'Světlý ležák plzeňského typu, do kterého je přidán čerství zelený chmel, který propůjčuje pivu ještě jemnější chuť a vůni s delším dozníváním hořkosti oproti klasickému ležáku.',price:'0,3 l 27 Kč~0,5 l 42 Kč'},
{data:'2019-10-01',name:'Robin ALE 12°(víkendová nabídka)',desc:'Lehké osvěžující pivo, které se vyznačuje zlatavou, téměř čirou barvou a sladovou vůní s nádechem citrusů. Střední hořkost doplňuje bylinná chuť s pryskyřičnými tóny.',price:'0,3 l 35 Kč~0,5 l 55 Kč'},
{data:'2019-09-18',name:'Vupitár ALE 11° (víkendová nabídka)',desc:'Lehký, velice pitelný ejl, který v aroma a chuti nebude pouze ovocný, ale i pryskyřičný a zemitý. Právě proto padla volba na kombinaci chmelů Simcoe a Amarillo.',price:'0,3 l 32 Kč~0,5 l 50 Kč'},
{data:'2019-09-05',name:'Krahulík 12°',desc:'Spodně kvašený ležák plzeňského typu vařený dvourmutovým způsobem z nejkvalitnějších moravských sladů, chmelený Žateckým poloraným červeňákem.',price:'0,3 l 30 Kč~0,5 l 45 Kč'},
{data:'2019-08-29',name:'Benedict ležák 12°',desc:'Klasická světlá dvanáctka vyrobená tradičním způsobem vyznačující se plností a silnou, ale jemnou hořkostí.',price:'0,3 l 30 Kč~0,5 l 45 Kč'},
{data:'2019-08-28',name:'Podřipský Pale Ale (víkendová nabídka)',desc:'Svrchně kvašené světlé pivo. Pivo se vyznačuje vyšší a zároveň jemnou příjemně doznívající hořkostí a lehkou vůní, kterou pivu propůjčuje australský chmel.',price:'0,3 l 32 Kč~0,5 l 47 Kč'},
{data:'2019-08-22',name:'Podřipský Pale Ale',desc:'Svrchně kvašené světlé pivo. Pivo se vyznačuje vyšší a zároveň jemnou příjemně doznívající hořkostí a lehkou vůní, kterou pivu propůjčuje australský chmel.',price:'0,3 l 32 Kč~0,5 l 47 Kč'},
{data:'2019-08-14',name:'Robin ALE 12° (víkendová nabídka)',desc:'Lehké osvěžující pivo, které se vyznačuje zlatavou, téměř čirou barvou a sladovou vůní s nádechem citrusů. Střední hořkost doplňuje bylinná chuť s pryskyřičnými tóny.',price:'0,3 l 35 Kč~0,5 l 55 Kč'},
{data:'2019-08-07',name:'Robin ALE 12°',desc:'Lehké osvěžující pivo, které se vyznačuje zlatavou, téměř čirou barvou a sladovou vůní s nádechem citrusů. Střední hořkost doplňuje bylinná chuť s pryskyřičnými tóny.',price:'0,3 l 35 Kč~0,5 l 55 Kč'},
{data:'2019-08-05',name:'Summer Ale 10°',desc:'Svrchně kvašené výčepní pivo typu Pale Ale. Velmi osvěžující v letních vedrech s vyšší hořkostí.',price:'0,3 l 30 Kč~0,5 l 46 Kč'},
{data:'2019-07-23',name:'Summer 9°',desc:'Světlé, hořce osvěžující pivo s chmelem Citra. Čtyřikrát chmelený speciál ze spilky s nezaměnitelným citrusovým aroma.',price:'0,3 l 28 Kč~0,5 l 44 Kč'},
{data:'2019-07-11',name:'Padre Fucho Ale 10°',desc:'Osvěžující, krásně lehké a skvěle pitelné. Tento letní „ejl“ se vyznačuje lehkou citrusovou vůní i chutí spolu s příjemnými chmelovými tóny. Povedená desítka, kterou zaženete žízeň.',price:'0,3 L / 32 Kč~0,5 L / 49 Kč'},
{data:'2019-07-08',name:'Padre Fucho Ale 10° (víkendová nabídka)',desc:'Osvěžující, krásně lehké a skvěle pitelné. Tento letní „ejl“ se vyznačuje lehkou citrusovou vůní i chutí spolu s příjemnými chmelovými tóny. Povedená desítka, kterou zaženete žízeň.',price:'0,3 L / 32 Kč~0,5 L / 49 Kč'},
{data:'2019-07-04',name:'PADRE FUCHO ALE 10° (víkendová nabídka)',desc:'Osvěžující, krásně lehké a skvěle pitelné. Tento letní ejl se vyznačuje lehkou citrusovou vůní i chutí spolu s příjemnými chmelovými tóny. Povedená desítka, kterou zaženete žízeň.',price:'0,3 L / 32 Kč~0,5 L / 49 Kč'},
{data:'2019-06-25',name:'Podřipský Summer ALE 10°',desc:'Svrchně kvašené výčepní pivo typu Pale Ale. Velmi osvěžující v letních vedrech s vyšší hořkostí.',price:'0,3 L  30 Kč~0,5 L  46 Kč'},
]},
{name:'nabidka-pivo-logo',data:[
{data:'2020-02-15',name:'https://www.pivoteka.cz/data/temp/product-images/15/falkenstejn-product-detail-large.jpg?v=2968890511',desc:'',price:''},
{data:'2020-01-28',name:'https://pivovari.cz/wp-content/uploads/2019/11/pivovar-libertas-logo.png',desc:'',price:''},
{data:'2019-12-19',name:'https://www.facebook.com/2263401717274380/photos/2314231165524768/',desc:'',price:''},
{data:'2019-12-18',name:'https://www.pivoteka-tabor.cz/user/documents/upload/Loga%20pivovar%C5%AF/falkenstejn.png',desc:'',price:''},
{data:'2019-12-02',name:'http://pivotekaberoun.bpivo.cz/pivotekaberoun/sites/default/files/pictures/stranky_katalogu_logo/Ostravar-logo-2010.jpg',desc:'',price:''},
{data:'2019-11-20',name:'http://www.slunceveskle.cz/wp-content/uploads/2013/08/Zichovec.png',desc:'',price:''},
{data:'2019-10-29',name:'https://www.pivoteka-tabor.cz/user/documents/upload/Loga%20pivovar%C5%AF/B%C5%99evnov.png',desc:'',price:''},
{data:'2019-10-11',name:'https://pivovary.info/prehled/ctineves/ctineves_logo.jpg',desc:'',price:''},
{data:'2019-07-17',name:'https://i.imgur.com/pOTaD7B.jpg',desc:'',price:''},
]},
] })
